// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_plant.proto

package pb_cs_plant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 土地结构
type Land struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CfgId             uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                         // 配置ID
	SeedId            uint32                 `protobuf:"varint,2,opt,name=SeedId,proto3" json:"SeedId,omitempty"`                       // 种子ID
	Level             uint32                 `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`                         // 土地等级
	PlantingTimestamp uint64                 `protobuf:"varint,4,opt,name=PlantingTimestamp,proto3" json:"PlantingTimestamp,omitempty"` // 种植时间戳
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Land) Reset() {
	*x = Land{}
	mi := &file_pb_cs_plant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Land) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Land) ProtoMessage() {}

func (x *Land) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Land.ProtoReflect.Descriptor instead.
func (*Land) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{0}
}

func (x *Land) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Land) GetSeedId() uint32 {
	if x != nil {
		return x.SeedId
	}
	return 0
}

func (x *Land) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Land) GetPlantingTimestamp() uint64 {
	if x != nil {
		return x.PlantingTimestamp
	}
	return 0
}

// 种植成功后会推送 402
type ReqPlanting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`   // 配置ID
	SeedId        uint32                 `protobuf:"varint,2,opt,name=SeedId,proto3" json:"SeedId,omitempty"` // 种子ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPlanting) Reset() {
	*x = ReqPlanting{}
	mi := &file_pb_cs_plant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPlanting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPlanting) ProtoMessage() {}

func (x *ReqPlanting) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPlanting.ProtoReflect.Descriptor instead.
func (*ReqPlanting) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPlanting) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ReqPlanting) GetSeedId() uint32 {
	if x != nil {
		return x.SeedId
	}
	return 0
}

// 收获成功后会推送 402
type ReqHarvest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqHarvest) Reset() {
	*x = ReqHarvest{}
	mi := &file_pb_cs_plant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqHarvest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqHarvest) ProtoMessage() {}

func (x *ReqHarvest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqHarvest.ProtoReflect.Descriptor instead.
func (*ReqHarvest) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{2}
}

func (x *ReqHarvest) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// 解锁后会推送 402
type ReqUnlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 配置ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUnlock) Reset() {
	*x = ReqUnlock{}
	mi := &file_pb_cs_plant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUnlock) ProtoMessage() {}

func (x *ReqUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUnlock.ProtoReflect.Descriptor instead.
func (*ReqUnlock) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUnlock) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

// 种植系统登录推送
type RepPlantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lands         []*Land                `protobuf:"bytes,1,rep,name=Lands,proto3" json:"Lands,omitempty"` // 解锁土地列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPlantInfo) Reset() {
	*x = RepPlantInfo{}
	mi := &file_pb_cs_plant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPlantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPlantInfo) ProtoMessage() {}

func (x *RepPlantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPlantInfo.ProtoReflect.Descriptor instead.
func (*RepPlantInfo) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{4}
}

func (x *RepPlantInfo) GetLands() []*Land {
	if x != nil {
		return x.Lands
	}
	return nil
}

// 种植土地更新
type RepPlantUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Land          *Land                  `protobuf:"bytes,1,opt,name=Land,proto3" json:"Land,omitempty"` // 土地信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPlantUpdate) Reset() {
	*x = RepPlantUpdate{}
	mi := &file_pb_cs_plant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPlantUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPlantUpdate) ProtoMessage() {}

func (x *RepPlantUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_plant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPlantUpdate.ProtoReflect.Descriptor instead.
func (*RepPlantUpdate) Descriptor() ([]byte, []int) {
	return file_pb_cs_plant_proto_rawDescGZIP(), []int{5}
}

func (x *RepPlantUpdate) GetLand() *Land {
	if x != nil {
		return x.Land
	}
	return nil
}

var File_pb_cs_plant_proto protoreflect.FileDescriptor

const file_pb_cs_plant_proto_rawDesc = "" +
	"\n" +
	"\x11pb_cs_plant.proto\x12\vpb_cs_plant\"x\n" +
	"\x04Land\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x16\n" +
	"\x06SeedId\x18\x02 \x01(\rR\x06SeedId\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\rR\x05Level\x12,\n" +
	"\x11PlantingTimestamp\x18\x04 \x01(\x04R\x11PlantingTimestamp\";\n" +
	"\vReqPlanting\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x16\n" +
	"\x06SeedId\x18\x02 \x01(\rR\x06SeedId\"\"\n" +
	"\n" +
	"ReqHarvest\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\"!\n" +
	"\tReqUnlock\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\"7\n" +
	"\fRepPlantInfo\x12'\n" +
	"\x05Lands\x18\x01 \x03(\v2\x11.pb_cs_plant.LandR\x05Lands\"7\n" +
	"\x0eRepPlantUpdate\x12%\n" +
	"\x04Land\x18\x01 \x01(\v2\x11.pb_cs_plant.LandR\x04LandB\x18Z\x16game/pb/cs/pb_cs_plantb\x06proto3"

var (
	file_pb_cs_plant_proto_rawDescOnce sync.Once
	file_pb_cs_plant_proto_rawDescData []byte
)

func file_pb_cs_plant_proto_rawDescGZIP() []byte {
	file_pb_cs_plant_proto_rawDescOnce.Do(func() {
		file_pb_cs_plant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_plant_proto_rawDesc), len(file_pb_cs_plant_proto_rawDesc)))
	})
	return file_pb_cs_plant_proto_rawDescData
}

var file_pb_cs_plant_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_cs_plant_proto_goTypes = []any{
	(*Land)(nil),           // 0: pb_cs_plant.Land
	(*ReqPlanting)(nil),    // 1: pb_cs_plant.ReqPlanting
	(*ReqHarvest)(nil),     // 2: pb_cs_plant.ReqHarvest
	(*ReqUnlock)(nil),      // 3: pb_cs_plant.ReqUnlock
	(*RepPlantInfo)(nil),   // 4: pb_cs_plant.RepPlantInfo
	(*RepPlantUpdate)(nil), // 5: pb_cs_plant.RepPlantUpdate
}
var file_pb_cs_plant_proto_depIdxs = []int32{
	0, // 0: pb_cs_plant.RepPlantInfo.Lands:type_name -> pb_cs_plant.Land
	0, // 1: pb_cs_plant.RepPlantUpdate.Land:type_name -> pb_cs_plant.Land
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_cs_plant_proto_init() }
func file_pb_cs_plant_proto_init() {
	if File_pb_cs_plant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_plant_proto_rawDesc), len(file_pb_cs_plant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_plant_proto_goTypes,
		DependencyIndexes: file_pb_cs_plant_proto_depIdxs,
		MessageInfos:      file_pb_cs_plant_proto_msgTypes,
	}.Build()
	File_pb_cs_plant_proto = out.File
	file_pb_cs_plant_proto_goTypes = nil
	file_pb_cs_plant_proto_depIdxs = nil
}
