// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_rpc_error.proto

package pb_rpc_error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码提示
type RepError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`                      // 错误码
	ArgsIntList   []uint32               `protobuf:"varint,2,rep,packed,name=ArgsIntList,proto3" json:"ArgsIntList,omitempty"` // int参数列表
	ArgsStrList   []string               `protobuf:"bytes,3,rep,name=ArgsStrList,proto3" json:"ArgsStrList,omitempty"`         // string参数列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepError) Reset() {
	*x = RepError{}
	mi := &file_pb_rpc_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepError) ProtoMessage() {}

func (x *RepError) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepError.ProtoReflect.Descriptor instead.
func (*RepError) Descriptor() ([]byte, []int) {
	return file_pb_rpc_error_proto_rawDescGZIP(), []int{0}
}

func (x *RepError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RepError) GetArgsIntList() []uint32 {
	if x != nil {
		return x.ArgsIntList
	}
	return nil
}

func (x *RepError) GetArgsStrList() []string {
	if x != nil {
		return x.ArgsStrList
	}
	return nil
}

var File_pb_rpc_error_proto protoreflect.FileDescriptor

const file_pb_rpc_error_proto_rawDesc = "" +
	"\n" +
	"\x12pb_rpc_error.proto\x12\fpb_rpc_error\"b\n" +
	"\bRepError\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\rR\x04Code\x12 \n" +
	"\vArgsIntList\x18\x02 \x03(\rR\vArgsIntList\x12 \n" +
	"\vArgsStrList\x18\x03 \x03(\tR\vArgsStrListB\x1aZ\x18game/pb/rpc/pb_rpc_errorb\x06proto3"

var (
	file_pb_rpc_error_proto_rawDescOnce sync.Once
	file_pb_rpc_error_proto_rawDescData []byte
)

func file_pb_rpc_error_proto_rawDescGZIP() []byte {
	file_pb_rpc_error_proto_rawDescOnce.Do(func() {
		file_pb_rpc_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_error_proto_rawDesc), len(file_pb_rpc_error_proto_rawDesc)))
	})
	return file_pb_rpc_error_proto_rawDescData
}

var file_pb_rpc_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_rpc_error_proto_goTypes = []any{
	(*RepError)(nil), // 0: pb_rpc_error.RepError
}
var file_pb_rpc_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_rpc_error_proto_init() }
func file_pb_rpc_error_proto_init() {
	if File_pb_rpc_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_error_proto_rawDesc), len(file_pb_rpc_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_error_proto_goTypes,
		DependencyIndexes: file_pb_rpc_error_proto_depIdxs,
		MessageInfos:      file_pb_rpc_error_proto_msgTypes,
	}.Build()
	File_pb_rpc_error_proto = out.File
	file_pb_rpc_error_proto_goTypes = nil
	file_pb_rpc_error_proto_depIdxs = nil
}
