// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_account.proto

package pb_cs_account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求随机名字和改名消耗
type ReqRandomName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqRandomName) Reset() {
	*x = ReqRandomName{}
	mi := &file_pb_cs_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqRandomName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRandomName) ProtoMessage() {}

func (x *ReqRandomName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRandomName.ProtoReflect.Descriptor instead.
func (*ReqRandomName) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{0}
}

// 玩家改名
type ReqChangeName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // 名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqChangeName) Reset() {
	*x = ReqChangeName{}
	mi := &file_pb_cs_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqChangeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangeName) ProtoMessage() {}

func (x *ReqChangeName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangeName.ProtoReflect.Descriptor instead.
func (*ReqChangeName) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{1}
}

func (x *ReqChangeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 输入兑换码
type ReqGiftCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"` // 兑换码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGiftCode) Reset() {
	*x = ReqGiftCode{}
	mi := &file_pb_cs_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGiftCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGiftCode) ProtoMessage() {}

func (x *ReqGiftCode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGiftCode.ProtoReflect.Descriptor instead.
func (*ReqGiftCode) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGiftCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 反馈
type ReqFeedBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` // 反馈内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqFeedBack) Reset() {
	*x = ReqFeedBack{}
	mi := &file_pb_cs_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFeedBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFeedBack) ProtoMessage() {}

func (x *ReqFeedBack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFeedBack.ProtoReflect.Descriptor instead.
func (*ReqFeedBack) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{3}
}

func (x *ReqFeedBack) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 账号信息登录推送(必要协议都发完才发这个，接着会发非必要的协议)
type RepPlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=Sid,proto3" json:"Sid,omitempty"`               // 角色ID
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`              // 名字
	Level         int32                  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`           // 等级
	Exp           uint32                 `protobuf:"varint,4,opt,name=Exp,proto3" json:"Exp,omitempty"`               // 经验
	SerId         uint32                 `protobuf:"varint,5,opt,name=SerId,proto3" json:"SerId,omitempty"`           // 服务器ID
	ShowId        uint32                 `protobuf:"varint,6,opt,name=ShowId,proto3" json:"ShowId,omitempty"`         // 服务器展示ID
	UserTag       uint32                 `protobuf:"varint,7,opt,name=UserTag,proto3" json:"UserTag,omitempty"`       // 用户分类(用来区分不同难度)
	CreateTime    uint32                 `protobuf:"varint,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"` // 注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPlayerInfo) Reset() {
	*x = RepPlayerInfo{}
	mi := &file_pb_cs_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPlayerInfo) ProtoMessage() {}

func (x *RepPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPlayerInfo.ProtoReflect.Descriptor instead.
func (*RepPlayerInfo) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{4}
}

func (x *RepPlayerInfo) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *RepPlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepPlayerInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RepPlayerInfo) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RepPlayerInfo) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *RepPlayerInfo) GetShowId() uint32 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *RepPlayerInfo) GetUserTag() uint32 {
	if x != nil {
		return x.UserTag
	}
	return 0
}

func (x *RepPlayerInfo) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 返回一个随机名字和改名消耗
type RepRandomName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // 玩家名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepRandomName) Reset() {
	*x = RepRandomName{}
	mi := &file_pb_cs_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepRandomName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepRandomName) ProtoMessage() {}

func (x *RepRandomName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepRandomName.ProtoReflect.Descriptor instead.
func (*RepRandomName) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{5}
}

func (x *RepRandomName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 玩家改名成功返回
type RepChangeName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // 玩家名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepChangeName) Reset() {
	*x = RepChangeName{}
	mi := &file_pb_cs_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepChangeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepChangeName) ProtoMessage() {}

func (x *RepChangeName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepChangeName.ProtoReflect.Descriptor instead.
func (*RepChangeName) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{6}
}

func (x *RepChangeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 玩家等级变化,或者经验变化推送
type RepLevelUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"` // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepLevelUp) Reset() {
	*x = RepLevelUp{}
	mi := &file_pb_cs_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepLevelUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepLevelUp) ProtoMessage() {}

func (x *RepLevelUp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepLevelUp.ProtoReflect.Descriptor instead.
func (*RepLevelUp) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{7}
}

func (x *RepLevelUp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 兑换码返回
type RepGiftCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`  // 是否使用成功
	FailMsg       string                 `protobuf:"bytes,2,opt,name=FailMsg,proto3" json:"FailMsg,omitempty"` // 失败提示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepGiftCode) Reset() {
	*x = RepGiftCode{}
	mi := &file_pb_cs_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepGiftCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepGiftCode) ProtoMessage() {}

func (x *RepGiftCode) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepGiftCode.ProtoReflect.Descriptor instead.
func (*RepGiftCode) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{8}
}

func (x *RepGiftCode) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *RepGiftCode) GetFailMsg() string {
	if x != nil {
		return x.FailMsg
	}
	return ""
}

// 反馈成功返回
type RepFeedBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepFeedBack) Reset() {
	*x = RepFeedBack{}
	mi := &file_pb_cs_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepFeedBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepFeedBack) ProtoMessage() {}

func (x *RepFeedBack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepFeedBack.ProtoReflect.Descriptor instead.
func (*RepFeedBack) Descriptor() ([]byte, []int) {
	return file_pb_cs_account_proto_rawDescGZIP(), []int{9}
}

var File_pb_cs_account_proto protoreflect.FileDescriptor

const file_pb_cs_account_proto_rawDesc = "" +
	"\n" +
	"\x13pb_cs_account.proto\x12\rpb_cs_account\"\x0f\n" +
	"\rReqRandomName\"#\n" +
	"\rReqChangeName\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"!\n" +
	"\vReqGiftCode\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\"'\n" +
	"\vReqFeedBack\x12\x18\n" +
	"\aContent\x18\x01 \x01(\tR\aContent\"\xc5\x01\n" +
	"\rRepPlayerInfo\x12\x10\n" +
	"\x03Sid\x18\x01 \x01(\rR\x03Sid\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\x05R\x05Level\x12\x10\n" +
	"\x03Exp\x18\x04 \x01(\rR\x03Exp\x12\x14\n" +
	"\x05SerId\x18\x05 \x01(\rR\x05SerId\x12\x16\n" +
	"\x06ShowId\x18\x06 \x01(\rR\x06ShowId\x12\x18\n" +
	"\aUserTag\x18\a \x01(\rR\aUserTag\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\b \x01(\rR\n" +
	"CreateTime\"#\n" +
	"\rRepRandomName\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"#\n" +
	"\rRepChangeName\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"\"\n" +
	"\n" +
	"RepLevelUp\x12\x14\n" +
	"\x05Level\x18\x01 \x01(\x05R\x05Level\"?\n" +
	"\vRepGiftCode\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\x12\x18\n" +
	"\aFailMsg\x18\x02 \x01(\tR\aFailMsg\"\r\n" +
	"\vRepFeedBackB\x1aZ\x18game/pb/cs/pb_cs_accountb\x06proto3"

var (
	file_pb_cs_account_proto_rawDescOnce sync.Once
	file_pb_cs_account_proto_rawDescData []byte
)

func file_pb_cs_account_proto_rawDescGZIP() []byte {
	file_pb_cs_account_proto_rawDescOnce.Do(func() {
		file_pb_cs_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_account_proto_rawDesc), len(file_pb_cs_account_proto_rawDesc)))
	})
	return file_pb_cs_account_proto_rawDescData
}

var file_pb_cs_account_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_cs_account_proto_goTypes = []any{
	(*ReqRandomName)(nil), // 0: pb_cs_account.ReqRandomName
	(*ReqChangeName)(nil), // 1: pb_cs_account.ReqChangeName
	(*ReqGiftCode)(nil),   // 2: pb_cs_account.ReqGiftCode
	(*ReqFeedBack)(nil),   // 3: pb_cs_account.ReqFeedBack
	(*RepPlayerInfo)(nil), // 4: pb_cs_account.RepPlayerInfo
	(*RepRandomName)(nil), // 5: pb_cs_account.RepRandomName
	(*RepChangeName)(nil), // 6: pb_cs_account.RepChangeName
	(*RepLevelUp)(nil),    // 7: pb_cs_account.RepLevelUp
	(*RepGiftCode)(nil),   // 8: pb_cs_account.RepGiftCode
	(*RepFeedBack)(nil),   // 9: pb_cs_account.RepFeedBack
}
var file_pb_cs_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_cs_account_proto_init() }
func file_pb_cs_account_proto_init() {
	if File_pb_cs_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_account_proto_rawDesc), len(file_pb_cs_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_account_proto_goTypes,
		DependencyIndexes: file_pb_cs_account_proto_depIdxs,
		MessageInfos:      file_pb_cs_account_proto_msgTypes,
	}.Build()
	File_pb_cs_account_proto = out.File
	file_pb_cs_account_proto_goTypes = nil
	file_pb_cs_account_proto_depIdxs = nil
}
