// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_pet.proto

package pb_cs_pet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 宠物结构
type Pet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`                     // 宠物UID
	CfgId         uint32                 `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                 // 配置ID
	Level         uint32                 `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`                 // 等级
	Exp           uint32                 `protobuf:"varint,4,opt,name=Exp,proto3" json:"Exp,omitempty"`                     // 经验
	Wears         []uint32               `protobuf:"varint,5,rep,packed,name=Wears,proto3" json:"Wears,omitempty"`          // 穿戴列表
	Satiety       uint32                 `protobuf:"varint,6,opt,name=Satiety,proto3" json:"Satiety,omitempty"`             // 饱食度
	FeedTimestamp int64                  `protobuf:"varint,7,opt,name=FeedTimestamp,proto3" json:"FeedTimestamp,omitempty"` // 喂食时间戳
	FeedTimes     uint32                 `protobuf:"varint,8,opt,name=FeedTimes,proto3" json:"FeedTimes,omitempty"`         // 喂食剩余次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_pb_cs_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Pet) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Pet) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Pet) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Pet) GetWears() []uint32 {
	if x != nil {
		return x.Wears
	}
	return nil
}

func (x *Pet) GetSatiety() uint32 {
	if x != nil {
		return x.Satiety
	}
	return 0
}

func (x *Pet) GetFeedTimestamp() int64 {
	if x != nil {
		return x.FeedTimestamp
	}
	return 0
}

func (x *Pet) GetFeedTimes() uint32 {
	if x != nil {
		return x.FeedTimes
	}
	return 0
}

// 穿戴服装请求 成功后会推送 1202
type ReqPutOnClothes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`               // 宠物UID
	ClothesUid    uint32                 `protobuf:"varint,2,opt,name=ClothesUid,proto3" json:"ClothesUid,omitempty"` // 服装Uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPutOnClothes) Reset() {
	*x = ReqPutOnClothes{}
	mi := &file_pb_cs_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPutOnClothes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPutOnClothes) ProtoMessage() {}

func (x *ReqPutOnClothes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPutOnClothes.ProtoReflect.Descriptor instead.
func (*ReqPutOnClothes) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPutOnClothes) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqPutOnClothes) GetClothesUid() uint32 {
	if x != nil {
		return x.ClothesUid
	}
	return 0
}

// 脱下服装请求 成功后会推送 1202
type ReqTakeOffClothes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`               // 宠物UID
	ClothesUid    uint32                 `protobuf:"varint,2,opt,name=ClothesUid,proto3" json:"ClothesUid,omitempty"` // 服装Uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTakeOffClothes) Reset() {
	*x = ReqTakeOffClothes{}
	mi := &file_pb_cs_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTakeOffClothes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTakeOffClothes) ProtoMessage() {}

func (x *ReqTakeOffClothes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTakeOffClothes.ProtoReflect.Descriptor instead.
func (*ReqTakeOffClothes) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{2}
}

func (x *ReqTakeOffClothes) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqTakeOffClothes) GetClothesUid() uint32 {
	if x != nil {
		return x.ClothesUid
	}
	return 0
}

// 喂养宠物 成功后会推送1202
type ReqFeedPet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`       // 宠物UID
	FoodId        uint32                 `protobuf:"varint,2,opt,name=FoodId,proto3" json:"FoodId,omitempty"` // 食物ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqFeedPet) Reset() {
	*x = ReqFeedPet{}
	mi := &file_pb_cs_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqFeedPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqFeedPet) ProtoMessage() {}

func (x *ReqFeedPet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqFeedPet.ProtoReflect.Descriptor instead.
func (*ReqFeedPet) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{3}
}

func (x *ReqFeedPet) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqFeedPet) GetFoodId() uint32 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

// 宠物信息登录推送
type RepPetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*Pet                 `protobuf:"bytes,1,rep,name=Pets,proto3" json:"Pets,omitempty"` // 宠物列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPetInfo) Reset() {
	*x = RepPetInfo{}
	mi := &file_pb_cs_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPetInfo) ProtoMessage() {}

func (x *RepPetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPetInfo.ProtoReflect.Descriptor instead.
func (*RepPetInfo) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{4}
}

func (x *RepPetInfo) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// 宠物信息变更推送
type RepPetUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pets          []*Pet                 `protobuf:"bytes,1,rep,name=Pets,proto3" json:"Pets,omitempty"` // 宠物列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPetUpdate) Reset() {
	*x = RepPetUpdate{}
	mi := &file_pb_cs_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPetUpdate) ProtoMessage() {}

func (x *RepPetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPetUpdate.ProtoReflect.Descriptor instead.
func (*RepPetUpdate) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{5}
}

func (x *RepPetUpdate) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// 单个宠物信息变更推送
type RepOnePetUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pet           *Pet                   `protobuf:"bytes,1,opt,name=Pet,proto3" json:"Pet,omitempty"` // 宠物信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepOnePetUpdate) Reset() {
	*x = RepOnePetUpdate{}
	mi := &file_pb_cs_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepOnePetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepOnePetUpdate) ProtoMessage() {}

func (x *RepOnePetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepOnePetUpdate.ProtoReflect.Descriptor instead.
func (*RepOnePetUpdate) Descriptor() ([]byte, []int) {
	return file_pb_cs_pet_proto_rawDescGZIP(), []int{6}
}

func (x *RepOnePetUpdate) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

var File_pb_cs_pet_proto protoreflect.FileDescriptor

const file_pb_cs_pet_proto_rawDesc = "" +
	"\n" +
	"\x0fpb_cs_pet.proto\x12\tpb_cs_pet\"\xc9\x01\n" +
	"\x03Pet\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\rR\x03Uid\x12\x14\n" +
	"\x05CfgId\x18\x02 \x01(\rR\x05CfgId\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\rR\x05Level\x12\x10\n" +
	"\x03Exp\x18\x04 \x01(\rR\x03Exp\x12\x14\n" +
	"\x05Wears\x18\x05 \x03(\rR\x05Wears\x12\x18\n" +
	"\aSatiety\x18\x06 \x01(\rR\aSatiety\x12$\n" +
	"\rFeedTimestamp\x18\a \x01(\x03R\rFeedTimestamp\x12\x1c\n" +
	"\tFeedTimes\x18\b \x01(\rR\tFeedTimes\"C\n" +
	"\x0fReqPutOnClothes\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\rR\x03Uid\x12\x1e\n" +
	"\n" +
	"ClothesUid\x18\x02 \x01(\rR\n" +
	"ClothesUid\"E\n" +
	"\x11ReqTakeOffClothes\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\rR\x03Uid\x12\x1e\n" +
	"\n" +
	"ClothesUid\x18\x02 \x01(\rR\n" +
	"ClothesUid\"6\n" +
	"\n" +
	"ReqFeedPet\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\rR\x03Uid\x12\x16\n" +
	"\x06FoodId\x18\x02 \x01(\rR\x06FoodId\"0\n" +
	"\n" +
	"RepPetInfo\x12\"\n" +
	"\x04Pets\x18\x01 \x03(\v2\x0e.pb_cs_pet.PetR\x04Pets\"2\n" +
	"\fRepPetUpdate\x12\"\n" +
	"\x04Pets\x18\x01 \x03(\v2\x0e.pb_cs_pet.PetR\x04Pets\"3\n" +
	"\x0fRepOnePetUpdate\x12 \n" +
	"\x03Pet\x18\x01 \x01(\v2\x0e.pb_cs_pet.PetR\x03PetB\x16Z\x14game/pb/cs/pb_cs_petb\x06proto3"

var (
	file_pb_cs_pet_proto_rawDescOnce sync.Once
	file_pb_cs_pet_proto_rawDescData []byte
)

func file_pb_cs_pet_proto_rawDescGZIP() []byte {
	file_pb_cs_pet_proto_rawDescOnce.Do(func() {
		file_pb_cs_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_pet_proto_rawDesc), len(file_pb_cs_pet_proto_rawDesc)))
	})
	return file_pb_cs_pet_proto_rawDescData
}

var file_pb_cs_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_cs_pet_proto_goTypes = []any{
	(*Pet)(nil),               // 0: pb_cs_pet.Pet
	(*ReqPutOnClothes)(nil),   // 1: pb_cs_pet.ReqPutOnClothes
	(*ReqTakeOffClothes)(nil), // 2: pb_cs_pet.ReqTakeOffClothes
	(*ReqFeedPet)(nil),        // 3: pb_cs_pet.ReqFeedPet
	(*RepPetInfo)(nil),        // 4: pb_cs_pet.RepPetInfo
	(*RepPetUpdate)(nil),      // 5: pb_cs_pet.RepPetUpdate
	(*RepOnePetUpdate)(nil),   // 6: pb_cs_pet.RepOnePetUpdate
}
var file_pb_cs_pet_proto_depIdxs = []int32{
	0, // 0: pb_cs_pet.RepPetInfo.Pets:type_name -> pb_cs_pet.Pet
	0, // 1: pb_cs_pet.RepPetUpdate.Pets:type_name -> pb_cs_pet.Pet
	0, // 2: pb_cs_pet.RepOnePetUpdate.Pet:type_name -> pb_cs_pet.Pet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_cs_pet_proto_init() }
func file_pb_cs_pet_proto_init() {
	if File_pb_cs_pet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_pet_proto_rawDesc), len(file_pb_cs_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_pet_proto_goTypes,
		DependencyIndexes: file_pb_cs_pet_proto_depIdxs,
		MessageInfos:      file_pb_cs_pet_proto_msgTypes,
	}.Build()
	File_pb_cs_pet_proto = out.File
	file_pb_cs_pet_proto_goTypes = nil
	file_pb_cs_pet_proto_depIdxs = nil
}
