// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_equip.proto

package pb_cs_equip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装备结构
type Equip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`     // 装备UID
	CfgId         uint32                 `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 配置ID
	Grade         uint32                 `protobuf:"varint,3,opt,name=Grade,proto3" json:"Grade,omitempty"` // 品质
	Level         uint32                 `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"` // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equip) Reset() {
	*x = Equip{}
	mi := &file_pb_cs_equip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equip) ProtoMessage() {}

func (x *Equip) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_equip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equip.ProtoReflect.Descriptor instead.
func (*Equip) Descriptor() ([]byte, []int) {
	return file_pb_cs_equip_proto_rawDescGZIP(), []int{0}
}

func (x *Equip) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Equip) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Equip) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Equip) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 装备信息登录批量推送
type RepAllEquips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equips        []*Equip               `protobuf:"bytes,1,rep,name=Equips,proto3" json:"Equips,omitempty"` // 装备信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepAllEquips) Reset() {
	*x = RepAllEquips{}
	mi := &file_pb_cs_equip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepAllEquips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepAllEquips) ProtoMessage() {}

func (x *RepAllEquips) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_equip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepAllEquips.ProtoReflect.Descriptor instead.
func (*RepAllEquips) Descriptor() ([]byte, []int) {
	return file_pb_cs_equip_proto_rawDescGZIP(), []int{1}
}

func (x *RepAllEquips) GetEquips() []*Equip {
	if x != nil {
		return x.Equips
	}
	return nil
}

// 装备更新
type RepUpdateEquips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Equips        []*Equip               `protobuf:"bytes,1,rep,name=Equips,proto3" json:"Equips,omitempty"` // 装备信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepUpdateEquips) Reset() {
	*x = RepUpdateEquips{}
	mi := &file_pb_cs_equip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepUpdateEquips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUpdateEquips) ProtoMessage() {}

func (x *RepUpdateEquips) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_equip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUpdateEquips.ProtoReflect.Descriptor instead.
func (*RepUpdateEquips) Descriptor() ([]byte, []int) {
	return file_pb_cs_equip_proto_rawDescGZIP(), []int{2}
}

func (x *RepUpdateEquips) GetEquips() []*Equip {
	if x != nil {
		return x.Equips
	}
	return nil
}

// 装备删除
type RepDelEquips struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []uint32               `protobuf:"varint,1,rep,packed,name=Uids,proto3" json:"Uids,omitempty"` // 删除的装备uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepDelEquips) Reset() {
	*x = RepDelEquips{}
	mi := &file_pb_cs_equip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepDelEquips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepDelEquips) ProtoMessage() {}

func (x *RepDelEquips) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_equip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepDelEquips.ProtoReflect.Descriptor instead.
func (*RepDelEquips) Descriptor() ([]byte, []int) {
	return file_pb_cs_equip_proto_rawDescGZIP(), []int{3}
}

func (x *RepDelEquips) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

var File_pb_cs_equip_proto protoreflect.FileDescriptor

const file_pb_cs_equip_proto_rawDesc = "" +
	"\n" +
	"\x11pb_cs_equip.proto\x12\vpb_cs_equip\"[\n" +
	"\x05Equip\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\rR\x03Uid\x12\x14\n" +
	"\x05CfgId\x18\x02 \x01(\rR\x05CfgId\x12\x14\n" +
	"\x05Grade\x18\x03 \x01(\rR\x05Grade\x12\x14\n" +
	"\x05Level\x18\x04 \x01(\rR\x05Level\":\n" +
	"\fRepAllEquips\x12*\n" +
	"\x06Equips\x18\x01 \x03(\v2\x12.pb_cs_equip.EquipR\x06Equips\"=\n" +
	"\x0fRepUpdateEquips\x12*\n" +
	"\x06Equips\x18\x01 \x03(\v2\x12.pb_cs_equip.EquipR\x06Equips\"\"\n" +
	"\fRepDelEquips\x12\x12\n" +
	"\x04Uids\x18\x01 \x03(\rR\x04UidsB\x18Z\x16game/pb/cs/pb_cs_equipb\x06proto3"

var (
	file_pb_cs_equip_proto_rawDescOnce sync.Once
	file_pb_cs_equip_proto_rawDescData []byte
)

func file_pb_cs_equip_proto_rawDescGZIP() []byte {
	file_pb_cs_equip_proto_rawDescOnce.Do(func() {
		file_pb_cs_equip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_equip_proto_rawDesc), len(file_pb_cs_equip_proto_rawDesc)))
	})
	return file_pb_cs_equip_proto_rawDescData
}

var file_pb_cs_equip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_cs_equip_proto_goTypes = []any{
	(*Equip)(nil),           // 0: pb_cs_equip.Equip
	(*RepAllEquips)(nil),    // 1: pb_cs_equip.RepAllEquips
	(*RepUpdateEquips)(nil), // 2: pb_cs_equip.RepUpdateEquips
	(*RepDelEquips)(nil),    // 3: pb_cs_equip.RepDelEquips
}
var file_pb_cs_equip_proto_depIdxs = []int32{
	0, // 0: pb_cs_equip.RepAllEquips.Equips:type_name -> pb_cs_equip.Equip
	0, // 1: pb_cs_equip.RepUpdateEquips.Equips:type_name -> pb_cs_equip.Equip
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_cs_equip_proto_init() }
func file_pb_cs_equip_proto_init() {
	if File_pb_cs_equip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_equip_proto_rawDesc), len(file_pb_cs_equip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_equip_proto_goTypes,
		DependencyIndexes: file_pb_cs_equip_proto_depIdxs,
		MessageInfos:      file_pb_cs_equip_proto_msgTypes,
	}.Build()
	File_pb_cs_equip_proto = out.File
	file_pb_cs_equip_proto_goTypes = nil
	file_pb_cs_equip_proto_depIdxs = nil
}
