// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_role.proto

package pb_cs_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设置当前宠物 成功后会推送 611
type ReqSetCurPet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        uint32                 `protobuf:"varint,1,opt,name=PetUid,proto3" json:"PetUid,omitempty"` // 设置的宠物Uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSetCurPet) Reset() {
	*x = ReqSetCurPet{}
	mi := &file_pb_cs_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSetCurPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSetCurPet) ProtoMessage() {}

func (x *ReqSetCurPet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSetCurPet.ProtoReflect.Descriptor instead.
func (*ReqSetCurPet) Descriptor() ([]byte, []int) {
	return file_pb_cs_role_proto_rawDescGZIP(), []int{0}
}

func (x *ReqSetCurPet) GetPetUid() uint32 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

// 英雄信息登录推送/变更推送
type RepRoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        uint32                 `protobuf:"varint,1,opt,name=PetUid,proto3" json:"PetUid,omitempty"` // 当前选中的宠物Uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepRoleInfo) Reset() {
	*x = RepRoleInfo{}
	mi := &file_pb_cs_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepRoleInfo) ProtoMessage() {}

func (x *RepRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepRoleInfo.ProtoReflect.Descriptor instead.
func (*RepRoleInfo) Descriptor() ([]byte, []int) {
	return file_pb_cs_role_proto_rawDescGZIP(), []int{1}
}

func (x *RepRoleInfo) GetPetUid() uint32 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

// 设置当前宠物返回
type RepSetCurPet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PetUid        uint32                 `protobuf:"varint,1,opt,name=PetUid,proto3" json:"PetUid,omitempty"` // 当前的宠物Uid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepSetCurPet) Reset() {
	*x = RepSetCurPet{}
	mi := &file_pb_cs_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepSetCurPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepSetCurPet) ProtoMessage() {}

func (x *RepSetCurPet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepSetCurPet.ProtoReflect.Descriptor instead.
func (*RepSetCurPet) Descriptor() ([]byte, []int) {
	return file_pb_cs_role_proto_rawDescGZIP(), []int{2}
}

func (x *RepSetCurPet) GetPetUid() uint32 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

var File_pb_cs_role_proto protoreflect.FileDescriptor

const file_pb_cs_role_proto_rawDesc = "" +
	"\n" +
	"\x10pb_cs_role.proto\x12\n" +
	"pb_cs_role\"&\n" +
	"\fReqSetCurPet\x12\x16\n" +
	"\x06PetUid\x18\x01 \x01(\rR\x06PetUid\"%\n" +
	"\vRepRoleInfo\x12\x16\n" +
	"\x06PetUid\x18\x01 \x01(\rR\x06PetUid\"&\n" +
	"\fRepSetCurPet\x12\x16\n" +
	"\x06PetUid\x18\x01 \x01(\rR\x06PetUidB\x17Z\x15game/pb/cs/pb_cs_roleb\x06proto3"

var (
	file_pb_cs_role_proto_rawDescOnce sync.Once
	file_pb_cs_role_proto_rawDescData []byte
)

func file_pb_cs_role_proto_rawDescGZIP() []byte {
	file_pb_cs_role_proto_rawDescOnce.Do(func() {
		file_pb_cs_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_role_proto_rawDesc), len(file_pb_cs_role_proto_rawDesc)))
	})
	return file_pb_cs_role_proto_rawDescData
}

var file_pb_cs_role_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_cs_role_proto_goTypes = []any{
	(*ReqSetCurPet)(nil), // 0: pb_cs_role.ReqSetCurPet
	(*RepRoleInfo)(nil),  // 1: pb_cs_role.RepRoleInfo
	(*RepSetCurPet)(nil), // 2: pb_cs_role.RepSetCurPet
}
var file_pb_cs_role_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_cs_role_proto_init() }
func file_pb_cs_role_proto_init() {
	if File_pb_cs_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_role_proto_rawDesc), len(file_pb_cs_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_role_proto_goTypes,
		DependencyIndexes: file_pb_cs_role_proto_depIdxs,
		MessageInfos:      file_pb_cs_role_proto_msgTypes,
	}.Build()
	File_pb_cs_role_proto = out.File
	file_pb_cs_role_proto_goTypes = nil
	file_pb_cs_role_proto_depIdxs = nil
}
