// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_item.proto

package pb_cs_item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品类型
type ItemType int32

const (
	ItemType_Source ItemType = 0 // 资源
	ItemType_Equip  ItemType = 1 // 装备
	ItemType_Box    ItemType = 2 // 宝箱
	ItemType_Role   ItemType = 3 // 英雄道具
	ItemType_Pet    ItemType = 4 // 宠物道具
	ItemType_Land   ItemType = 5 // 地块道具
	ItemType_Seed   ItemType = 6 // 种子道具
	ItemType_Fruit  ItemType = 7 // 果实道具
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "Source",
		1: "Equip",
		2: "Box",
		3: "Role",
		4: "Pet",
		5: "Land",
		6: "Seed",
		7: "Fruit",
	}
	ItemType_value = map[string]int32{
		"Source": 0,
		"Equip":  1,
		"Box":    2,
		"Role":   3,
		"Pet":    4,
		"Land":   5,
		"Seed":   6,
		"Fruit":  7,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_item_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_pb_cs_item_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{0}
}

// 物品ID
type ItemId int32

const (
	ItemId_None          ItemId = 0   // 未定义
	ItemId_Diamond       ItemId = 101 // 钻石
	ItemId_Gold          ItemId = 102 // 金币
	ItemId_Exp           ItemId = 103 // 经验
	ItemId_Stamina       ItemId = 104 // 体力
	ItemId_SevenDayPoint ItemId = 108 // 七日活跃积分
)

// Enum value maps for ItemId.
var (
	ItemId_name = map[int32]string{
		0:   "None",
		101: "Diamond",
		102: "Gold",
		103: "Exp",
		104: "Stamina",
		108: "SevenDayPoint",
	}
	ItemId_value = map[string]int32{
		"None":          0,
		"Diamond":       101,
		"Gold":          102,
		"Exp":           103,
		"Stamina":       104,
		"SevenDayPoint": 108,
	}
)

func (x ItemId) Enum() *ItemId {
	p := new(ItemId)
	*p = x
	return p
}

func (x ItemId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemId) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_item_proto_enumTypes[1].Descriptor()
}

func (ItemId) Type() protoreflect.EnumType {
	return &file_pb_cs_item_proto_enumTypes[1]
}

func (x ItemId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemId.Descriptor instead.
func (ItemId) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{1}
}

// 宝箱类型
type BoxType int32

const (
	BoxType_No     BoxType = 0 // 无效果
	BoxType_Choose BoxType = 1 // 自选
	BoxType_Auto   BoxType = 2 // 自动使用
)

// Enum value maps for BoxType.
var (
	BoxType_name = map[int32]string{
		0: "No",
		1: "Choose",
		2: "Auto",
	}
	BoxType_value = map[string]int32{
		"No":     0,
		"Choose": 1,
		"Auto":   2,
	}
)

func (x BoxType) Enum() *BoxType {
	p := new(BoxType)
	*p = x
	return p
}

func (x BoxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoxType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_item_proto_enumTypes[2].Descriptor()
}

func (BoxType) Type() protoreflect.EnumType {
	return &file_pb_cs_item_proto_enumTypes[2]
}

func (x BoxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoxType.Descriptor instead.
func (BoxType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{2}
}

// 物品结构
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`       // 配置ID
	StackNum      uint64                 `protobuf:"varint,2,opt,name=StackNum,proto3" json:"StackNum,omitempty"` // 物品堆叠数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_pb_cs_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Item) GetStackNum() uint64 {
	if x != nil {
		return x.StackNum
	}
	return 0
}

// 使用物品
type ReqUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`        // 物品配置ID
	Num           uint32                 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`            // 使用物品次数
	ItemsList     []*Item                `protobuf:"bytes,3,rep,name=ItemsList,proto3" json:"ItemsList,omitempty"` // 物品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUseItem) Reset() {
	*x = ReqUseItem{}
	mi := &file_pb_cs_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUseItem) ProtoMessage() {}

func (x *ReqUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUseItem.ProtoReflect.Descriptor instead.
func (*ReqUseItem) Descriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{1}
}

func (x *ReqUseItem) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ReqUseItem) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ReqUseItem) GetItemsList() []*Item {
	if x != nil {
		return x.ItemsList
	}
	return nil
}

// 物品信息登录批量推送
type RepAllItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsList     []*Item                `protobuf:"bytes,1,rep,name=ItemsList,proto3" json:"ItemsList,omitempty"` // 物品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepAllItems) Reset() {
	*x = RepAllItems{}
	mi := &file_pb_cs_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepAllItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepAllItems) ProtoMessage() {}

func (x *RepAllItems) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepAllItems.ProtoReflect.Descriptor instead.
func (*RepAllItems) Descriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{2}
}

func (x *RepAllItems) GetItemsList() []*Item {
	if x != nil {
		return x.ItemsList
	}
	return nil
}

// 物品增量更新
type RepUpdateItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemsList     []*Item                `protobuf:"bytes,1,rep,name=ItemsList,proto3" json:"ItemsList,omitempty"` // 物品信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepUpdateItems) Reset() {
	*x = RepUpdateItems{}
	mi := &file_pb_cs_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepUpdateItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUpdateItems) ProtoMessage() {}

func (x *RepUpdateItems) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUpdateItems.ProtoReflect.Descriptor instead.
func (*RepUpdateItems) Descriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{3}
}

func (x *RepUpdateItems) GetItemsList() []*Item {
	if x != nil {
		return x.ItemsList
	}
	return nil
}

// 使用物品返回
type RepUseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"` // 物品配置ID
	Num           uint32                 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`     // 使用物品次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepUseItem) Reset() {
	*x = RepUseItem{}
	mi := &file_pb_cs_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUseItem) ProtoMessage() {}

func (x *RepUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUseItem.ProtoReflect.Descriptor instead.
func (*RepUseItem) Descriptor() ([]byte, []int) {
	return file_pb_cs_item_proto_rawDescGZIP(), []int{4}
}

func (x *RepUseItem) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *RepUseItem) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_pb_cs_item_proto protoreflect.FileDescriptor

const file_pb_cs_item_proto_rawDesc = "" +
	"\n" +
	"\x10pb_cs_item.proto\x12\n" +
	"pb_cs_item\"8\n" +
	"\x04Item\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x1a\n" +
	"\bStackNum\x18\x02 \x01(\x04R\bStackNum\"d\n" +
	"\n" +
	"ReqUseItem\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\rR\x03Num\x12.\n" +
	"\tItemsList\x18\x03 \x03(\v2\x10.pb_cs_item.ItemR\tItemsList\"=\n" +
	"\vRepAllItems\x12.\n" +
	"\tItemsList\x18\x01 \x03(\v2\x10.pb_cs_item.ItemR\tItemsList\"@\n" +
	"\x0eRepUpdateItems\x12.\n" +
	"\tItemsList\x18\x01 \x03(\v2\x10.pb_cs_item.ItemR\tItemsList\"4\n" +
	"\n" +
	"RepUseItem\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\rR\x03Num*\\\n" +
	"\bItemType\x12\n" +
	"\n" +
	"\x06Source\x10\x00\x12\t\n" +
	"\x05Equip\x10\x01\x12\a\n" +
	"\x03Box\x10\x02\x12\b\n" +
	"\x04Role\x10\x03\x12\a\n" +
	"\x03Pet\x10\x04\x12\b\n" +
	"\x04Land\x10\x05\x12\b\n" +
	"\x04Seed\x10\x06\x12\t\n" +
	"\x05Fruit\x10\a*R\n" +
	"\x06ItemId\x12\b\n" +
	"\x04None\x10\x00\x12\v\n" +
	"\aDiamond\x10e\x12\b\n" +
	"\x04Gold\x10f\x12\a\n" +
	"\x03Exp\x10g\x12\v\n" +
	"\aStamina\x10h\x12\x11\n" +
	"\rSevenDayPoint\x10l*'\n" +
	"\aBoxType\x12\x06\n" +
	"\x02No\x10\x00\x12\n" +
	"\n" +
	"\x06Choose\x10\x01\x12\b\n" +
	"\x04Auto\x10\x02B\x17Z\x15game/pb/cs/pb_cs_itemb\x06proto3"

var (
	file_pb_cs_item_proto_rawDescOnce sync.Once
	file_pb_cs_item_proto_rawDescData []byte
)

func file_pb_cs_item_proto_rawDescGZIP() []byte {
	file_pb_cs_item_proto_rawDescOnce.Do(func() {
		file_pb_cs_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_item_proto_rawDesc), len(file_pb_cs_item_proto_rawDesc)))
	})
	return file_pb_cs_item_proto_rawDescData
}

var file_pb_cs_item_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pb_cs_item_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_cs_item_proto_goTypes = []any{
	(ItemType)(0),          // 0: pb_cs_item.ItemType
	(ItemId)(0),            // 1: pb_cs_item.ItemId
	(BoxType)(0),           // 2: pb_cs_item.BoxType
	(*Item)(nil),           // 3: pb_cs_item.Item
	(*ReqUseItem)(nil),     // 4: pb_cs_item.ReqUseItem
	(*RepAllItems)(nil),    // 5: pb_cs_item.RepAllItems
	(*RepUpdateItems)(nil), // 6: pb_cs_item.RepUpdateItems
	(*RepUseItem)(nil),     // 7: pb_cs_item.RepUseItem
}
var file_pb_cs_item_proto_depIdxs = []int32{
	3, // 0: pb_cs_item.ReqUseItem.ItemsList:type_name -> pb_cs_item.Item
	3, // 1: pb_cs_item.RepAllItems.ItemsList:type_name -> pb_cs_item.Item
	3, // 2: pb_cs_item.RepUpdateItems.ItemsList:type_name -> pb_cs_item.Item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_cs_item_proto_init() }
func file_pb_cs_item_proto_init() {
	if File_pb_cs_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_item_proto_rawDesc), len(file_pb_cs_item_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_item_proto_goTypes,
		DependencyIndexes: file_pb_cs_item_proto_depIdxs,
		EnumInfos:         file_pb_cs_item_proto_enumTypes,
		MessageInfos:      file_pb_cs_item_proto_msgTypes,
	}.Build()
	File_pb_cs_item_proto = out.File
	file_pb_cs_item_proto_goTypes = nil
	file_pb_cs_item_proto_depIdxs = nil
}
