// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_login.proto

package pb_cs_login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SDK类型
type Sdk int32

const (
	Sdk_UNDEFINED Sdk = 0    // 未定义
	Sdk_Test      Sdk = 9999 // 内网(无登录验证)
	Sdk_PetWorld  Sdk = 2    // 宠物世界平台
)

// Enum value maps for Sdk.
var (
	Sdk_name = map[int32]string{
		0:    "UNDEFINED",
		9999: "Test",
		2:    "PetWorld",
	}
	Sdk_value = map[string]int32{
		"UNDEFINED": 0,
		"Test":      9999,
		"PetWorld":  2,
	}
)

func (x Sdk) Enum() *Sdk {
	p := new(Sdk)
	*p = x
	return p
}

func (x Sdk) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sdk) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_login_proto_enumTypes[0].Descriptor()
}

func (Sdk) Type() protoreflect.EnumType {
	return &file_pb_cs_login_proto_enumTypes[0]
}

func (x Sdk) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sdk.Descriptor instead.
func (Sdk) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{0}
}

// 登陆返回
type LoginResult int32

const (
	LoginResult_Success       LoginResult = 0 // 登陆成功
	LoginResult_AuthFailed    LoginResult = 1 // SDK验证失败
	LoginResult_ReconnectFail LoginResult = 2 // 超过最大重连时间
	LoginResult_SdkError      LoginResult = 3 // 未接入该SDK
	LoginResult_UserNull      LoginResult = 4 // 账号为空
	LoginResult_TokenNull     LoginResult = 5 // Token为空
)

// Enum value maps for LoginResult.
var (
	LoginResult_name = map[int32]string{
		0: "Success",
		1: "AuthFailed",
		2: "ReconnectFail",
		3: "SdkError",
		4: "UserNull",
		5: "TokenNull",
	}
	LoginResult_value = map[string]int32{
		"Success":       0,
		"AuthFailed":    1,
		"ReconnectFail": 2,
		"SdkError":      3,
		"UserNull":      4,
		"TokenNull":     5,
	}
)

func (x LoginResult) Enum() *LoginResult {
	p := new(LoginResult)
	*p = x
	return p
}

func (x LoginResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResult) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_login_proto_enumTypes[1].Descriptor()
}

func (LoginResult) Type() protoreflect.EnumType {
	return &file_pb_cs_login_proto_enumTypes[1]
}

func (x LoginResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResult.Descriptor instead.
func (LoginResult) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{1}
}

// 账号当前状态
type LoginAccStatus int32

const (
	LoginAccStatus_Normal LoginAccStatus = 0 // 普通登录
	LoginAccStatus_Create LoginAccStatus = 1 // 创角登录
)

// Enum value maps for LoginAccStatus.
var (
	LoginAccStatus_name = map[int32]string{
		0: "Normal",
		1: "Create",
	}
	LoginAccStatus_value = map[string]int32{
		"Normal": 0,
		"Create": 1,
	}
)

func (x LoginAccStatus) Enum() *LoginAccStatus {
	p := new(LoginAccStatus)
	*p = x
	return p
}

func (x LoginAccStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginAccStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_login_proto_enumTypes[2].Descriptor()
}

func (LoginAccStatus) Type() protoreflect.EnumType {
	return &file_pb_cs_login_proto_enumTypes[2]
}

func (x LoginAccStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginAccStatus.Descriptor instead.
func (LoginAccStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{2}
}

// 重连类型
type ReconnectType int32

const (
	ReconnectType_Common ReconnectType = 0 // 普通
	ReconnectType_Quick  ReconnectType = 1 // 快速
)

// Enum value maps for ReconnectType.
var (
	ReconnectType_name = map[int32]string{
		0: "Common",
		1: "Quick",
	}
	ReconnectType_value = map[string]int32{
		"Common": 0,
		"Quick":  1,
	}
)

func (x ReconnectType) Enum() *ReconnectType {
	p := new(ReconnectType)
	*p = x
	return p
}

func (x ReconnectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconnectType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_login_proto_enumTypes[3].Descriptor()
}

func (ReconnectType) Type() protoreflect.EnumType {
	return &file_pb_cs_login_proto_enumTypes[3]
}

func (x ReconnectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconnectType.Descriptor instead.
func (ReconnectType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{3}
}

// 登陆
type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SdkId         Sdk                    `protobuf:"varint,1,opt,name=SdkId,proto3,enum=pb_cs_login.Sdk" json:"SdkId,omitempty"` // 接入的sdkID,游戏自定义 const@SDK
	User          string                 `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`                         // 平台账号
	Imei          string                 `protobuf:"bytes,3,opt,name=Imei,proto3" json:"Imei,omitempty"`                         // 设备号
	SerId         uint32                 `protobuf:"varint,4,opt,name=SerId,proto3" json:"SerId,omitempty"`                      // 服务器ID
	IsWhite       bool                   `protobuf:"varint,5,opt,name=IsWhite,proto3" json:"IsWhite,omitempty"`                  // 是否白名单
	Token         string                 `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`                       // token
	Version       string                 `protobuf:"bytes,7,opt,name=Version,proto3" json:"Version,omitempty"`                   // 版本号
	Os            uint32                 `protobuf:"varint,8,opt,name=Os,proto3" json:"Os,omitempty"`                            // 操作系统
	Sign          string                 `protobuf:"bytes,9,opt,name=Sign,proto3" json:"Sign,omitempty"`                         // 签名,json_data+key的MD5,服务器用来做校验
	JsonData      string                 `protobuf:"bytes,10,opt,name=JsonData,proto3" json:"JsonData,omitempty"`                // 前端从平台获取的用户数据信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_pb_cs_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetSdkId() Sdk {
	if x != nil {
		return x.SdkId
	}
	return Sdk_UNDEFINED
}

func (x *ReqLogin) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReqLogin) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *ReqLogin) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *ReqLogin) GetIsWhite() bool {
	if x != nil {
		return x.IsWhite
	}
	return false
}

func (x *ReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReqLogin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReqLogin) GetOs() uint32 {
	if x != nil {
		return x.Os
	}
	return 0
}

func (x *ReqLogin) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *ReqLogin) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// ping同步时间
type ReqPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint32                 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"` // 客户端发起请求时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPing) Reset() {
	*x = ReqPing{}
	mi := &file_pb_cs_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPing) ProtoMessage() {}

func (x *ReqPing) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPing.ProtoReflect.Descriptor instead.
func (*ReqPing) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPing) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 断线重连(上次离线后n小时内可用,绕过sdk登陆)
type ReqReconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=Sid,proto3" json:"Sid,omitempty"`                                  // 玩家ID
	Imei          string                 `protobuf:"bytes,2,opt,name=Imei,proto3" json:"Imei,omitempty"`                                 // 设备号
	Type          ReconnectType          `protobuf:"varint,3,opt,name=Type,proto3,enum=pb_cs_login.ReconnectType" json:"Type,omitempty"` // 重连类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqReconnect) Reset() {
	*x = ReqReconnect{}
	mi := &file_pb_cs_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqReconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqReconnect) ProtoMessage() {}

func (x *ReqReconnect) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqReconnect.ProtoReflect.Descriptor instead.
func (*ReqReconnect) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{2}
}

func (x *ReqReconnect) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ReqReconnect) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *ReqReconnect) GetType() ReconnectType {
	if x != nil {
		return x.Type
	}
	return ReconnectType_Common
}

// 网关服请求初始化player
type ReqGateInitPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=Sid,proto3" json:"Sid,omitempty"`       // 玩家ID
	GateId        uint32                 `protobuf:"varint,2,opt,name=GateId,proto3" json:"GateId,omitempty"` // 网关ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGateInitPlayer) Reset() {
	*x = ReqGateInitPlayer{}
	mi := &file_pb_cs_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGateInitPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGateInitPlayer) ProtoMessage() {}

func (x *ReqGateInitPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGateInitPlayer.ProtoReflect.Descriptor instead.
func (*ReqGateInitPlayer) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{3}
}

func (x *ReqGateInitPlayer) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ReqGateInitPlayer) GetGateId() uint32 {
	if x != nil {
		return x.GateId
	}
	return 0
}

// 客户端通知修改数据
type ReqClientUpdateAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=JsonData,proto3" json:"JsonData,omitempty"` // 前端从平台获取的用户数据信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqClientUpdateAccount) Reset() {
	*x = ReqClientUpdateAccount{}
	mi := &file_pb_cs_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqClientUpdateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqClientUpdateAccount) ProtoMessage() {}

func (x *ReqClientUpdateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqClientUpdateAccount.ProtoReflect.Descriptor instead.
func (*ReqClientUpdateAccount) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{4}
}

func (x *ReqClientUpdateAccount) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// 登陆返回
type RepLoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errorcode     LoginResult            `protobuf:"varint,1,opt,name=Errorcode,proto3,enum=pb_cs_login.LoginResult" json:"Errorcode,omitempty"`    // 状态码
	Sid           uint32                 `protobuf:"varint,2,opt,name=Sid,proto3" json:"Sid,omitempty"`                                             // 玩家ID
	SerId         uint32                 `protobuf:"varint,3,opt,name=SerId,proto3" json:"SerId,omitempty"`                                         // 服务器ID
	AccStatus     LoginAccStatus         `protobuf:"varint,4,opt,name=AccStatus,proto3,enum=pb_cs_login.LoginAccStatus" json:"AccStatus,omitempty"` // 账号当前状态
	Msg           string                 `protobuf:"bytes,5,opt,name=Msg,proto3" json:"Msg,omitempty"`                                              // 验证失败时的附带信息
	Time          uint32                 `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`                                           // 服务器收到请求时间戳
	IsGm          bool                   `protobuf:"varint,7,opt,name=IsGm,proto3" json:"IsGm,omitempty"`                                           // 是否gm账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepLoginResult) Reset() {
	*x = RepLoginResult{}
	mi := &file_pb_cs_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepLoginResult) ProtoMessage() {}

func (x *RepLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepLoginResult.ProtoReflect.Descriptor instead.
func (*RepLoginResult) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{5}
}

func (x *RepLoginResult) GetErrorcode() LoginResult {
	if x != nil {
		return x.Errorcode
	}
	return LoginResult_Success
}

func (x *RepLoginResult) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *RepLoginResult) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *RepLoginResult) GetAccStatus() LoginAccStatus {
	if x != nil {
		return x.AccStatus
	}
	return LoginAccStatus_Normal
}

func (x *RepLoginResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RepLoginResult) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RepLoginResult) GetIsGm() bool {
	if x != nil {
		return x.IsGm
	}
	return false
}

// pong同步时间
type RepPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          uint32                 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"` // 服务器收到请求时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPong) Reset() {
	*x = RepPong{}
	mi := &file_pb_cs_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPong) ProtoMessage() {}

func (x *RepPong) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPong.ProtoReflect.Descriptor instead.
func (*RepPong) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{6}
}

func (x *RepPong) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 所有登陆协议发放完成通知
type RepLoginInfoFinish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepLoginInfoFinish) Reset() {
	*x = RepLoginInfoFinish{}
	mi := &file_pb_cs_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepLoginInfoFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepLoginInfoFinish) ProtoMessage() {}

func (x *RepLoginInfoFinish) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepLoginInfoFinish.ProtoReflect.Descriptor instead.
func (*RepLoginInfoFinish) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{7}
}

// 网关服请求初始化player
type RepGateInitPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=Sid,proto3" json:"Sid,omitempty"` // 玩家ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepGateInitPlayer) Reset() {
	*x = RepGateInitPlayer{}
	mi := &file_pb_cs_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepGateInitPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepGateInitPlayer) ProtoMessage() {}

func (x *RepGateInitPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepGateInitPlayer.ProtoReflect.Descriptor instead.
func (*RepGateInitPlayer) Descriptor() ([]byte, []int) {
	return file_pb_cs_login_proto_rawDescGZIP(), []int{8}
}

func (x *RepGateInitPlayer) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

var File_pb_cs_login_proto protoreflect.FileDescriptor

const file_pb_cs_login_proto_rawDesc = "" +
	"\n" +
	"\x11pb_cs_login.proto\x12\vpb_cs_login\"\xfa\x01\n" +
	"\bReqLogin\x12&\n" +
	"\x05SdkId\x18\x01 \x01(\x0e2\x10.pb_cs_login.SdkR\x05SdkId\x12\x12\n" +
	"\x04User\x18\x02 \x01(\tR\x04User\x12\x12\n" +
	"\x04Imei\x18\x03 \x01(\tR\x04Imei\x12\x14\n" +
	"\x05SerId\x18\x04 \x01(\rR\x05SerId\x12\x18\n" +
	"\aIsWhite\x18\x05 \x01(\bR\aIsWhite\x12\x14\n" +
	"\x05Token\x18\x06 \x01(\tR\x05Token\x12\x18\n" +
	"\aVersion\x18\a \x01(\tR\aVersion\x12\x0e\n" +
	"\x02Os\x18\b \x01(\rR\x02Os\x12\x12\n" +
	"\x04Sign\x18\t \x01(\tR\x04Sign\x12\x1a\n" +
	"\bJsonData\x18\n" +
	" \x01(\tR\bJsonData\"\x1d\n" +
	"\aReqPing\x12\x12\n" +
	"\x04Time\x18\x01 \x01(\rR\x04Time\"d\n" +
	"\fReqReconnect\x12\x10\n" +
	"\x03Sid\x18\x01 \x01(\rR\x03Sid\x12\x12\n" +
	"\x04Imei\x18\x02 \x01(\tR\x04Imei\x12.\n" +
	"\x04Type\x18\x03 \x01(\x0e2\x1a.pb_cs_login.ReconnectTypeR\x04Type\"=\n" +
	"\x11ReqGateInitPlayer\x12\x10\n" +
	"\x03Sid\x18\x01 \x01(\rR\x03Sid\x12\x16\n" +
	"\x06GateId\x18\x02 \x01(\rR\x06GateId\"4\n" +
	"\x16ReqClientUpdateAccount\x12\x1a\n" +
	"\bJsonData\x18\x01 \x01(\tR\bJsonData\"\xe5\x01\n" +
	"\x0eRepLoginResult\x126\n" +
	"\tErrorcode\x18\x01 \x01(\x0e2\x18.pb_cs_login.LoginResultR\tErrorcode\x12\x10\n" +
	"\x03Sid\x18\x02 \x01(\rR\x03Sid\x12\x14\n" +
	"\x05SerId\x18\x03 \x01(\rR\x05SerId\x129\n" +
	"\tAccStatus\x18\x04 \x01(\x0e2\x1b.pb_cs_login.LoginAccStatusR\tAccStatus\x12\x10\n" +
	"\x03Msg\x18\x05 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Time\x18\x06 \x01(\rR\x04Time\x12\x12\n" +
	"\x04IsGm\x18\a \x01(\bR\x04IsGm\"\x1d\n" +
	"\aRepPong\x12\x12\n" +
	"\x04Time\x18\x01 \x01(\rR\x04Time\"\x14\n" +
	"\x12RepLoginInfoFinish\"%\n" +
	"\x11RepGateInitPlayer\x12\x10\n" +
	"\x03Sid\x18\x01 \x01(\rR\x03Sid*-\n" +
	"\x03Sdk\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\t\n" +
	"\x04Test\x10\x8fN\x12\f\n" +
	"\bPetWorld\x10\x02*h\n" +
	"\vLoginResult\x12\v\n" +
	"\aSuccess\x10\x00\x12\x0e\n" +
	"\n" +
	"AuthFailed\x10\x01\x12\x11\n" +
	"\rReconnectFail\x10\x02\x12\f\n" +
	"\bSdkError\x10\x03\x12\f\n" +
	"\bUserNull\x10\x04\x12\r\n" +
	"\tTokenNull\x10\x05*(\n" +
	"\x0eLoginAccStatus\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\n" +
	"\n" +
	"\x06Create\x10\x01*&\n" +
	"\rReconnectType\x12\n" +
	"\n" +
	"\x06Common\x10\x00\x12\t\n" +
	"\x05Quick\x10\x01B\x18Z\x16game/pb/cs/pb_cs_loginb\x06proto3"

var (
	file_pb_cs_login_proto_rawDescOnce sync.Once
	file_pb_cs_login_proto_rawDescData []byte
)

func file_pb_cs_login_proto_rawDescGZIP() []byte {
	file_pb_cs_login_proto_rawDescOnce.Do(func() {
		file_pb_cs_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_login_proto_rawDesc), len(file_pb_cs_login_proto_rawDesc)))
	})
	return file_pb_cs_login_proto_rawDescData
}

var file_pb_cs_login_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pb_cs_login_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_cs_login_proto_goTypes = []any{
	(Sdk)(0),                       // 0: pb_cs_login.Sdk
	(LoginResult)(0),               // 1: pb_cs_login.LoginResult
	(LoginAccStatus)(0),            // 2: pb_cs_login.LoginAccStatus
	(ReconnectType)(0),             // 3: pb_cs_login.ReconnectType
	(*ReqLogin)(nil),               // 4: pb_cs_login.ReqLogin
	(*ReqPing)(nil),                // 5: pb_cs_login.ReqPing
	(*ReqReconnect)(nil),           // 6: pb_cs_login.ReqReconnect
	(*ReqGateInitPlayer)(nil),      // 7: pb_cs_login.ReqGateInitPlayer
	(*ReqClientUpdateAccount)(nil), // 8: pb_cs_login.ReqClientUpdateAccount
	(*RepLoginResult)(nil),         // 9: pb_cs_login.RepLoginResult
	(*RepPong)(nil),                // 10: pb_cs_login.RepPong
	(*RepLoginInfoFinish)(nil),     // 11: pb_cs_login.RepLoginInfoFinish
	(*RepGateInitPlayer)(nil),      // 12: pb_cs_login.RepGateInitPlayer
}
var file_pb_cs_login_proto_depIdxs = []int32{
	0, // 0: pb_cs_login.ReqLogin.SdkId:type_name -> pb_cs_login.Sdk
	3, // 1: pb_cs_login.ReqReconnect.Type:type_name -> pb_cs_login.ReconnectType
	1, // 2: pb_cs_login.RepLoginResult.Errorcode:type_name -> pb_cs_login.LoginResult
	2, // 3: pb_cs_login.RepLoginResult.AccStatus:type_name -> pb_cs_login.LoginAccStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_cs_login_proto_init() }
func file_pb_cs_login_proto_init() {
	if File_pb_cs_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_login_proto_rawDesc), len(file_pb_cs_login_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_login_proto_goTypes,
		DependencyIndexes: file_pb_cs_login_proto_depIdxs,
		EnumInfos:         file_pb_cs_login_proto_enumTypes,
		MessageInfos:      file_pb_cs_login_proto_msgTypes,
	}.Build()
	File_pb_cs_login_proto = out.File
	file_pb_cs_login_proto_goTypes = nil
	file_pb_cs_login_proto_depIdxs = nil
}
