// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_rpc_gmail.proto

package pb_rpc_gmail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 道具奖励列表
type ItemReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`       // 配置ID
	StackNum      uint64                 `protobuf:"varint,2,opt,name=StackNum,proto3" json:"StackNum,omitempty"` // 数量
	Grade         uint32                 `protobuf:"varint,3,opt,name=Grade,proto3" json:"Grade,omitempty"`       // 品质
	Level         uint32                 `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`       // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReward) Reset() {
	*x = ItemReward{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReward) ProtoMessage() {}

func (x *ItemReward) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReward.ProtoReflect.Descriptor instead.
func (*ItemReward) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{0}
}

func (x *ItemReward) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemReward) GetStackNum() uint64 {
	if x != nil {
		return x.StackNum
	}
	return 0
}

func (x *ItemReward) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ItemReward) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 邮件
type Gmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`     // 标题
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"` // 内容
	Rewards       []*ItemReward          `protobuf:"bytes,3,rep,name=Rewards,proto3" json:"Rewards,omitempty"` // 奖励列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gmail) Reset() {
	*x = Gmail{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gmail) ProtoMessage() {}

func (x *Gmail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gmail.ProtoReflect.Descriptor instead.
func (*Gmail) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{1}
}

func (x *Gmail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Gmail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Gmail) GetRewards() []*ItemReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

// 发送全局邮件
type ReqSendGmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerId         uint32                 `protobuf:"varint,1,opt,name=SerId,proto3" json:"SerId,omitempty"` // 服务器ID
	Mail          *Gmail                 `protobuf:"bytes,2,opt,name=Mail,proto3" json:"Mail,omitempty"`    // 邮件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSendGmail) Reset() {
	*x = ReqSendGmail{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendGmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendGmail) ProtoMessage() {}

func (x *ReqSendGmail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendGmail.ProtoReflect.Descriptor instead.
func (*ReqSendGmail) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{2}
}

func (x *ReqSendGmail) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *ReqSendGmail) GetMail() *Gmail {
	if x != nil {
		return x.Mail
	}
	return nil
}

// 发送个人邮件
type ReqSendUserMail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerId         uint32                 `protobuf:"varint,1,opt,name=SerId,proto3" json:"SerId,omitempty"` // 服务器ID
	Sid           uint32                 `protobuf:"varint,2,opt,name=Sid,proto3" json:"Sid,omitempty"`     // 服务器ID
	Mail          *Gmail                 `protobuf:"bytes,3,opt,name=Mail,proto3" json:"Mail,omitempty"`    // 邮件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqSendUserMail) Reset() {
	*x = ReqSendUserMail{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqSendUserMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSendUserMail) ProtoMessage() {}

func (x *ReqSendUserMail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSendUserMail.ProtoReflect.Descriptor instead.
func (*ReqSendUserMail) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSendUserMail) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *ReqSendUserMail) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ReqSendUserMail) GetMail() *Gmail {
	if x != nil {
		return x.Mail
	}
	return nil
}

// 发送全局邮件返回
type RepSendGmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"` // 发送结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepSendGmail) Reset() {
	*x = RepSendGmail{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepSendGmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepSendGmail) ProtoMessage() {}

func (x *RepSendGmail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepSendGmail.ProtoReflect.Descriptor instead.
func (*RepSendGmail) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{4}
}

func (x *RepSendGmail) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// 发送个人邮件
type RepSendUserMail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"` // 发送结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepSendUserMail) Reset() {
	*x = RepSendUserMail{}
	mi := &file_pb_rpc_gmail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepSendUserMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepSendUserMail) ProtoMessage() {}

func (x *RepSendUserMail) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gmail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepSendUserMail.ProtoReflect.Descriptor instead.
func (*RepSendUserMail) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gmail_proto_rawDescGZIP(), []int{5}
}

func (x *RepSendUserMail) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_pb_rpc_gmail_proto protoreflect.FileDescriptor

const file_pb_rpc_gmail_proto_rawDesc = "" +
	"\n" +
	"\x12pb_rpc_gmail.proto\x12\fpb_rpc_gmail\"j\n" +
	"\n" +
	"ItemReward\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x1a\n" +
	"\bStackNum\x18\x02 \x01(\x04R\bStackNum\x12\x14\n" +
	"\x05Grade\x18\x03 \x01(\rR\x05Grade\x12\x14\n" +
	"\x05Level\x18\x04 \x01(\rR\x05Level\"k\n" +
	"\x05Gmail\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x122\n" +
	"\aRewards\x18\x03 \x03(\v2\x18.pb_rpc_gmail.ItemRewardR\aRewards\"M\n" +
	"\fReqSendGmail\x12\x14\n" +
	"\x05SerId\x18\x01 \x01(\rR\x05SerId\x12'\n" +
	"\x04Mail\x18\x02 \x01(\v2\x13.pb_rpc_gmail.GmailR\x04Mail\"b\n" +
	"\x0fReqSendUserMail\x12\x14\n" +
	"\x05SerId\x18\x01 \x01(\rR\x05SerId\x12\x10\n" +
	"\x03Sid\x18\x02 \x01(\rR\x03Sid\x12'\n" +
	"\x04Mail\x18\x03 \x01(\v2\x13.pb_rpc_gmail.GmailR\x04Mail\"&\n" +
	"\fRepSendGmail\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\")\n" +
	"\x0fRepSendUserMail\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06ResultB\x1aZ\x18game/pb/rpc/pb_rpc_gmailb\x06proto3"

var (
	file_pb_rpc_gmail_proto_rawDescOnce sync.Once
	file_pb_rpc_gmail_proto_rawDescData []byte
)

func file_pb_rpc_gmail_proto_rawDescGZIP() []byte {
	file_pb_rpc_gmail_proto_rawDescOnce.Do(func() {
		file_pb_rpc_gmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_gmail_proto_rawDesc), len(file_pb_rpc_gmail_proto_rawDesc)))
	})
	return file_pb_rpc_gmail_proto_rawDescData
}

var file_pb_rpc_gmail_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_rpc_gmail_proto_goTypes = []any{
	(*ItemReward)(nil),      // 0: pb_rpc_gmail.ItemReward
	(*Gmail)(nil),           // 1: pb_rpc_gmail.Gmail
	(*ReqSendGmail)(nil),    // 2: pb_rpc_gmail.ReqSendGmail
	(*ReqSendUserMail)(nil), // 3: pb_rpc_gmail.ReqSendUserMail
	(*RepSendGmail)(nil),    // 4: pb_rpc_gmail.RepSendGmail
	(*RepSendUserMail)(nil), // 5: pb_rpc_gmail.RepSendUserMail
}
var file_pb_rpc_gmail_proto_depIdxs = []int32{
	0, // 0: pb_rpc_gmail.Gmail.Rewards:type_name -> pb_rpc_gmail.ItemReward
	1, // 1: pb_rpc_gmail.ReqSendGmail.Mail:type_name -> pb_rpc_gmail.Gmail
	1, // 2: pb_rpc_gmail.ReqSendUserMail.Mail:type_name -> pb_rpc_gmail.Gmail
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_rpc_gmail_proto_init() }
func file_pb_rpc_gmail_proto_init() {
	if File_pb_rpc_gmail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_gmail_proto_rawDesc), len(file_pb_rpc_gmail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_gmail_proto_goTypes,
		DependencyIndexes: file_pb_rpc_gmail_proto_depIdxs,
		MessageInfos:      file_pb_rpc_gmail_proto_msgTypes,
	}.Build()
	File_pb_rpc_gmail_proto = out.File
	file_pb_rpc_gmail_proto_goTypes = nil
	file_pb_rpc_gmail_proto_depIdxs = nil
}
