// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_rpc_gm.proto

package pb_rpc_gm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 前端服务器显示状态
type ShowState int32

const (
	ShowState_Normal    ShowState = 0 // 正常
	ShowState_Busy      ShowState = 1 // 繁忙
	ShowState_Crowd     ShowState = 2 // 拥挤
	ShowState_Close     ShowState = 3 // 维护中
	ShowState_Recommend ShowState = 4 // 推荐
)

// Enum value maps for ShowState.
var (
	ShowState_name = map[int32]string{
		0: "Normal",
		1: "Busy",
		2: "Crowd",
		3: "Close",
		4: "Recommend",
	}
	ShowState_value = map[string]int32{
		"Normal":    0,
		"Busy":      1,
		"Crowd":     2,
		"Close":     3,
		"Recommend": 4,
	}
)

func (x ShowState) Enum() *ShowState {
	p := new(ShowState)
	*p = x
	return p
}

func (x ShowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShowState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_rpc_gm_proto_enumTypes[0].Descriptor()
}

func (ShowState) Type() protoreflect.EnumType {
	return &file_pb_rpc_gm_proto_enumTypes[0]
}

func (x ShowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShowState.Descriptor instead.
func (ShowState) EnumDescriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{0}
}

// 服务器状态
type ServerState int32

const (
	ServerState_Running ServerState = 0 // 开启
	ServerState_Down    ServerState = 1 // 关闭
)

// Enum value maps for ServerState.
var (
	ServerState_name = map[int32]string{
		0: "Running",
		1: "Down",
	}
	ServerState_value = map[string]int32{
		"Running": 0,
		"Down":    1,
	}
)

func (x ServerState) Enum() *ServerState {
	p := new(ServerState)
	*p = x
	return p
}

func (x ServerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_rpc_gm_proto_enumTypes[1].Descriptor()
}

func (ServerState) Type() protoreflect.EnumType {
	return &file_pb_rpc_gm_proto_enumTypes[1]
}

func (x ServerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerState.Descriptor instead.
func (ServerState) EnumDescriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{1}
}

// 区服管理信息
type Gm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerId         uint32                 `protobuf:"varint,1,opt,name=SerId,proto3" json:"SerId,omitempty"`                                  // 区服ID
	SerName       string                 `protobuf:"bytes,2,opt,name=SerName,proto3" json:"SerName,omitempty"`                               // 区服名称
	ShowState     ShowState              `protobuf:"varint,3,opt,name=ShowState,proto3,enum=pb_rpc_gm.ShowState" json:"ShowState,omitempty"` // 前端展示状态
	State         ServerState            `protobuf:"varint,4,opt,name=State,proto3,enum=pb_rpc_gm.ServerState" json:"State,omitempty"`       // 后端状态
	GameVersion   string                 `protobuf:"bytes,5,opt,name=GameVersion,proto3" json:"GameVersion,omitempty"`                       // 版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gm) Reset() {
	*x = Gm{}
	mi := &file_pb_rpc_gm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gm) ProtoMessage() {}

func (x *Gm) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gm.ProtoReflect.Descriptor instead.
func (*Gm) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{0}
}

func (x *Gm) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *Gm) GetSerName() string {
	if x != nil {
		return x.SerName
	}
	return ""
}

func (x *Gm) GetShowState() ShowState {
	if x != nil {
		return x.ShowState
	}
	return ShowState_Normal
}

func (x *Gm) GetState() ServerState {
	if x != nil {
		return x.State
	}
	return ServerState_Running
}

func (x *Gm) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

// gm信息更新:acc
type ReqGmUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gms           []*Gm                  `protobuf:"bytes,1,rep,name=Gms,proto3" json:"Gms,omitempty"` // 区服管理信息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGmUpdate) Reset() {
	*x = ReqGmUpdate{}
	mi := &file_pb_rpc_gm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGmUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGmUpdate) ProtoMessage() {}

func (x *ReqGmUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGmUpdate.ProtoReflect.Descriptor instead.
func (*ReqGmUpdate) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGmUpdate) GetGms() []*Gm {
	if x != nil {
		return x.Gms
	}
	return nil
}

// 账号信息更新:acc
type ReqAccReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerId         uint32                 `protobuf:"varint,1,opt,name=SerId,proto3" json:"SerId,omitempty"`         // 区服ID
	AccNum        uint32                 `protobuf:"varint,2,opt,name=AccNum,proto3" json:"AccNum,omitempty"`       // 账号数
	OnlineNum     uint32                 `protobuf:"varint,3,opt,name=OnlineNum,proto3" json:"OnlineNum,omitempty"` // 在线人数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqAccReport) Reset() {
	*x = ReqAccReport{}
	mi := &file_pb_rpc_gm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqAccReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAccReport) ProtoMessage() {}

func (x *ReqAccReport) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAccReport.ProtoReflect.Descriptor instead.
func (*ReqAccReport) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{2}
}

func (x *ReqAccReport) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *ReqAccReport) GetAccNum() uint32 {
	if x != nil {
		return x.AccNum
	}
	return 0
}

func (x *ReqAccReport) GetOnlineNum() uint32 {
	if x != nil {
		return x.OnlineNum
	}
	return 0
}

// gm信息更新返回
type RepGmUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"` // 更新结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepGmUpdate) Reset() {
	*x = RepGmUpdate{}
	mi := &file_pb_rpc_gm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepGmUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepGmUpdate) ProtoMessage() {}

func (x *RepGmUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepGmUpdate.ProtoReflect.Descriptor instead.
func (*RepGmUpdate) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{3}
}

func (x *RepGmUpdate) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// 账号信息更新:acc
type RepAccReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"` // 更新结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepAccReport) Reset() {
	*x = RepAccReport{}
	mi := &file_pb_rpc_gm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepAccReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepAccReport) ProtoMessage() {}

func (x *RepAccReport) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_gm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepAccReport.ProtoReflect.Descriptor instead.
func (*RepAccReport) Descriptor() ([]byte, []int) {
	return file_pb_rpc_gm_proto_rawDescGZIP(), []int{4}
}

func (x *RepAccReport) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_pb_rpc_gm_proto protoreflect.FileDescriptor

const file_pb_rpc_gm_proto_rawDesc = "" +
	"\n" +
	"\x0fpb_rpc_gm.proto\x12\tpb_rpc_gm\"\xb8\x01\n" +
	"\x02Gm\x12\x14\n" +
	"\x05SerId\x18\x01 \x01(\rR\x05SerId\x12\x18\n" +
	"\aSerName\x18\x02 \x01(\tR\aSerName\x122\n" +
	"\tShowState\x18\x03 \x01(\x0e2\x14.pb_rpc_gm.ShowStateR\tShowState\x12,\n" +
	"\x05State\x18\x04 \x01(\x0e2\x16.pb_rpc_gm.ServerStateR\x05State\x12 \n" +
	"\vGameVersion\x18\x05 \x01(\tR\vGameVersion\".\n" +
	"\vReqGmUpdate\x12\x1f\n" +
	"\x03Gms\x18\x01 \x03(\v2\r.pb_rpc_gm.GmR\x03Gms\"Z\n" +
	"\fReqAccReport\x12\x14\n" +
	"\x05SerId\x18\x01 \x01(\rR\x05SerId\x12\x16\n" +
	"\x06AccNum\x18\x02 \x01(\rR\x06AccNum\x12\x1c\n" +
	"\tOnlineNum\x18\x03 \x01(\rR\tOnlineNum\"%\n" +
	"\vRepGmUpdate\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result\"&\n" +
	"\fRepAccReport\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\bR\x06Result*F\n" +
	"\tShowState\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\b\n" +
	"\x04Busy\x10\x01\x12\t\n" +
	"\x05Crowd\x10\x02\x12\t\n" +
	"\x05Close\x10\x03\x12\r\n" +
	"\tRecommend\x10\x04*$\n" +
	"\vServerState\x12\v\n" +
	"\aRunning\x10\x00\x12\b\n" +
	"\x04Down\x10\x01B\x17Z\x15game/pb/rpc/pb_rpc_gmb\x06proto3"

var (
	file_pb_rpc_gm_proto_rawDescOnce sync.Once
	file_pb_rpc_gm_proto_rawDescData []byte
)

func file_pb_rpc_gm_proto_rawDescGZIP() []byte {
	file_pb_rpc_gm_proto_rawDescOnce.Do(func() {
		file_pb_rpc_gm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_gm_proto_rawDesc), len(file_pb_rpc_gm_proto_rawDesc)))
	})
	return file_pb_rpc_gm_proto_rawDescData
}

var file_pb_rpc_gm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_rpc_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_rpc_gm_proto_goTypes = []any{
	(ShowState)(0),       // 0: pb_rpc_gm.ShowState
	(ServerState)(0),     // 1: pb_rpc_gm.ServerState
	(*Gm)(nil),           // 2: pb_rpc_gm.Gm
	(*ReqGmUpdate)(nil),  // 3: pb_rpc_gm.ReqGmUpdate
	(*ReqAccReport)(nil), // 4: pb_rpc_gm.ReqAccReport
	(*RepGmUpdate)(nil),  // 5: pb_rpc_gm.RepGmUpdate
	(*RepAccReport)(nil), // 6: pb_rpc_gm.RepAccReport
}
var file_pb_rpc_gm_proto_depIdxs = []int32{
	0, // 0: pb_rpc_gm.Gm.ShowState:type_name -> pb_rpc_gm.ShowState
	1, // 1: pb_rpc_gm.Gm.State:type_name -> pb_rpc_gm.ServerState
	2, // 2: pb_rpc_gm.ReqGmUpdate.Gms:type_name -> pb_rpc_gm.Gm
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_rpc_gm_proto_init() }
func file_pb_rpc_gm_proto_init() {
	if File_pb_rpc_gm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_gm_proto_rawDesc), len(file_pb_rpc_gm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_gm_proto_goTypes,
		DependencyIndexes: file_pb_rpc_gm_proto_depIdxs,
		EnumInfos:         file_pb_rpc_gm_proto_enumTypes,
		MessageInfos:      file_pb_rpc_gm_proto_msgTypes,
	}.Build()
	File_pb_rpc_gm_proto = out.File
	file_pb_rpc_gm_proto_goTypes = nil
	file_pb_rpc_gm_proto_depIdxs = nil
}
