// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_travel.proto

package pb_cs_travel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 旅行事件类型
type EventType int32

const (
	EventType_EventNone      EventType = 0 // 忽略
	EventType_PetFeed        EventType = 1 // 宠物投喂
	EventType_ReceiveRewards EventType = 2 // 领取奖励
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EventNone",
		1: "PetFeed",
		2: "ReceiveRewards",
	}
	EventType_value = map[string]int32{
		"EventNone":      0,
		"PetFeed":        1,
		"ReceiveRewards": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_travel_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_pb_cs_travel_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{0}
}

// 条件表
type ConditionType int32

const (
	ConditionType_ConditionNone ConditionType = 0 // 忽略
	ConditionType_Satiety       ConditionType = 1 // 饱食度
	ConditionType_Charm         ConditionType = 2 // 魅力值
)

// Enum value maps for ConditionType.
var (
	ConditionType_name = map[int32]string{
		0: "ConditionNone",
		1: "Satiety",
		2: "Charm",
	}
	ConditionType_value = map[string]int32{
		"ConditionNone": 0,
		"Satiety":       1,
		"Charm":         2,
	}
)

func (x ConditionType) Enum() *ConditionType {
	p := new(ConditionType)
	*p = x
	return p
}

func (x ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_travel_proto_enumTypes[1].Descriptor()
}

func (ConditionType) Type() protoreflect.EnumType {
	return &file_pb_cs_travel_proto_enumTypes[1]
}

func (x ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionType.Descriptor instead.
func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{1}
}

// 旅行结构
type Travel struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CfgId          uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`                   // 配置ID
	PetUid         uint32                 `protobuf:"varint,2,opt,name=PetUid,proto3" json:"PetUid,omitempty"`                 // 宠物UID
	StartTimestamp uint64                 `protobuf:"varint,3,opt,name=StartTimestamp,proto3" json:"StartTimestamp,omitempty"` // 触发旅行时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Travel) Reset() {
	*x = Travel{}
	mi := &file_pb_cs_travel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Travel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Travel) ProtoMessage() {}

func (x *Travel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_travel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Travel.ProtoReflect.Descriptor instead.
func (*Travel) Descriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{0}
}

func (x *Travel) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *Travel) GetPetUid() uint32 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

func (x *Travel) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

// 领取旅行奖励
type ReqGetReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`   // 配置ID
	PetUid        uint32                 `protobuf:"varint,2,opt,name=PetUid,proto3" json:"PetUid,omitempty"` // 宠物UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetReward) Reset() {
	*x = ReqGetReward{}
	mi := &file_pb_cs_travel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetReward) ProtoMessage() {}

func (x *ReqGetReward) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_travel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetReward.ProtoReflect.Descriptor instead.
func (*ReqGetReward) Descriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetReward) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ReqGetReward) GetPetUid() uint32 {
	if x != nil {
		return x.PetUid
	}
	return 0
}

// 旅行系统登录推送
type RepTravelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Travels       []*Travel              `protobuf:"bytes,1,rep,name=Travels,proto3" json:"Travels,omitempty"` // 宠物旅行列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepTravelInfo) Reset() {
	*x = RepTravelInfo{}
	mi := &file_pb_cs_travel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepTravelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepTravelInfo) ProtoMessage() {}

func (x *RepTravelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_travel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepTravelInfo.ProtoReflect.Descriptor instead.
func (*RepTravelInfo) Descriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{2}
}

func (x *RepTravelInfo) GetTravels() []*Travel {
	if x != nil {
		return x.Travels
	}
	return nil
}

// 旅行更新
type RepTravelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Travel        *Travel                `protobuf:"bytes,1,opt,name=Travel,proto3" json:"Travel,omitempty"` // 宠物旅行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepTravelUpdate) Reset() {
	*x = RepTravelUpdate{}
	mi := &file_pb_cs_travel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepTravelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepTravelUpdate) ProtoMessage() {}

func (x *RepTravelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_travel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepTravelUpdate.ProtoReflect.Descriptor instead.
func (*RepTravelUpdate) Descriptor() ([]byte, []int) {
	return file_pb_cs_travel_proto_rawDescGZIP(), []int{3}
}

func (x *RepTravelUpdate) GetTravel() *Travel {
	if x != nil {
		return x.Travel
	}
	return nil
}

var File_pb_cs_travel_proto protoreflect.FileDescriptor

const file_pb_cs_travel_proto_rawDesc = "" +
	"\n" +
	"\x12pb_cs_travel.proto\x12\fpb_cs_travel\"^\n" +
	"\x06Travel\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x16\n" +
	"\x06PetUid\x18\x02 \x01(\rR\x06PetUid\x12&\n" +
	"\x0eStartTimestamp\x18\x03 \x01(\x04R\x0eStartTimestamp\"<\n" +
	"\fReqGetReward\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x16\n" +
	"\x06PetUid\x18\x02 \x01(\rR\x06PetUid\"?\n" +
	"\rRepTravelInfo\x12.\n" +
	"\aTravels\x18\x01 \x03(\v2\x14.pb_cs_travel.TravelR\aTravels\"?\n" +
	"\x0fRepTravelUpdate\x12,\n" +
	"\x06Travel\x18\x01 \x01(\v2\x14.pb_cs_travel.TravelR\x06Travel*;\n" +
	"\tEventType\x12\r\n" +
	"\tEventNone\x10\x00\x12\v\n" +
	"\aPetFeed\x10\x01\x12\x12\n" +
	"\x0eReceiveRewards\x10\x02*:\n" +
	"\rConditionType\x12\x11\n" +
	"\rConditionNone\x10\x00\x12\v\n" +
	"\aSatiety\x10\x01\x12\t\n" +
	"\x05Charm\x10\x02B\x19Z\x17game/pb/cs/pb_cs_travelb\x06proto3"

var (
	file_pb_cs_travel_proto_rawDescOnce sync.Once
	file_pb_cs_travel_proto_rawDescData []byte
)

func file_pb_cs_travel_proto_rawDescGZIP() []byte {
	file_pb_cs_travel_proto_rawDescOnce.Do(func() {
		file_pb_cs_travel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_travel_proto_rawDesc), len(file_pb_cs_travel_proto_rawDesc)))
	})
	return file_pb_cs_travel_proto_rawDescData
}

var file_pb_cs_travel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_cs_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_cs_travel_proto_goTypes = []any{
	(EventType)(0),          // 0: pb_cs_travel.EventType
	(ConditionType)(0),      // 1: pb_cs_travel.ConditionType
	(*Travel)(nil),          // 2: pb_cs_travel.Travel
	(*ReqGetReward)(nil),    // 3: pb_cs_travel.ReqGetReward
	(*RepTravelInfo)(nil),   // 4: pb_cs_travel.RepTravelInfo
	(*RepTravelUpdate)(nil), // 5: pb_cs_travel.RepTravelUpdate
}
var file_pb_cs_travel_proto_depIdxs = []int32{
	2, // 0: pb_cs_travel.RepTravelInfo.Travels:type_name -> pb_cs_travel.Travel
	2, // 1: pb_cs_travel.RepTravelUpdate.Travel:type_name -> pb_cs_travel.Travel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_cs_travel_proto_init() }
func file_pb_cs_travel_proto_init() {
	if File_pb_cs_travel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_travel_proto_rawDesc), len(file_pb_cs_travel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_travel_proto_goTypes,
		DependencyIndexes: file_pb_cs_travel_proto_depIdxs,
		EnumInfos:         file_pb_cs_travel_proto_enumTypes,
		MessageInfos:      file_pb_cs_travel_proto_msgTypes,
	}.Build()
	File_pb_cs_travel_proto = out.File
	file_pb_cs_travel_proto_goTypes = nil
	file_pb_cs_travel_proto_depIdxs = nil
}
