// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_rpc_cache.proto

package pb_rpc_cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 性别
type Sex int32

const (
	Sex_None  Sex = 0 // 未定义性别
	Sex_Man   Sex = 1 // 男
	Sex_Woman Sex = 2 // 女
)

// Enum value maps for Sex.
var (
	Sex_name = map[int32]string{
		0: "None",
		1: "Man",
		2: "Woman",
	}
	Sex_value = map[string]int32{
		"None":  0,
		"Man":   1,
		"Woman": 2,
	}
)

func (x Sex) Enum() *Sex {
	p := new(Sex)
	*p = x
	return p
}

func (x Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_rpc_cache_proto_enumTypes[0].Descriptor()
}

func (Sex) Type() protoreflect.EnumType {
	return &file_pb_rpc_cache_proto_enumTypes[0]
}

func (x Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sex.Descriptor instead.
func (Sex) EnumDescriptor() ([]byte, []int) {
	return file_pb_rpc_cache_proto_rawDescGZIP(), []int{0}
}

// cache查找
type ReqCacheLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // tab
	Sid           uint32                 `protobuf:"varint,2,opt,name=Sid,proto3" json:"Sid,omitempty"`  // sid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCacheLookup) Reset() {
	*x = ReqCacheLookup{}
	mi := &file_pb_rpc_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCacheLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCacheLookup) ProtoMessage() {}

func (x *ReqCacheLookup) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCacheLookup.ProtoReflect.Descriptor instead.
func (*ReqCacheLookup) Descriptor() ([]byte, []int) {
	return file_pb_rpc_cache_proto_rawDescGZIP(), []int{0}
}

func (x *ReqCacheLookup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqCacheLookup) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

// cache查找返回
type RepCacheLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=Sid,proto3" json:"Sid,omitempty"` // sid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepCacheLookup) Reset() {
	*x = RepCacheLookup{}
	mi := &file_pb_rpc_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepCacheLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepCacheLookup) ProtoMessage() {}

func (x *RepCacheLookup) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepCacheLookup.ProtoReflect.Descriptor instead.
func (*RepCacheLookup) Descriptor() ([]byte, []int) {
	return file_pb_rpc_cache_proto_rawDescGZIP(), []int{1}
}

func (x *RepCacheLookup) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

var File_pb_rpc_cache_proto protoreflect.FileDescriptor

const file_pb_rpc_cache_proto_rawDesc = "" +
	"\n" +
	"\x12pb_rpc_cache.proto\x12\fpb_rpc_cache\"6\n" +
	"\x0eReqCacheLookup\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x10\n" +
	"\x03Sid\x18\x02 \x01(\rR\x03Sid\"\"\n" +
	"\x0eRepCacheLookup\x12\x10\n" +
	"\x03Sid\x18\x01 \x01(\rR\x03Sid*#\n" +
	"\x03Sex\x12\b\n" +
	"\x04None\x10\x00\x12\a\n" +
	"\x03Man\x10\x01\x12\t\n" +
	"\x05Woman\x10\x02B\x1aZ\x18game/pb/rpc/pb_rpc_cacheb\x06proto3"

var (
	file_pb_rpc_cache_proto_rawDescOnce sync.Once
	file_pb_rpc_cache_proto_rawDescData []byte
)

func file_pb_rpc_cache_proto_rawDescGZIP() []byte {
	file_pb_rpc_cache_proto_rawDescOnce.Do(func() {
		file_pb_rpc_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_cache_proto_rawDesc), len(file_pb_rpc_cache_proto_rawDesc)))
	})
	return file_pb_rpc_cache_proto_rawDescData
}

var file_pb_rpc_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_rpc_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_rpc_cache_proto_goTypes = []any{
	(Sex)(0),               // 0: pb_rpc_cache.Sex
	(*ReqCacheLookup)(nil), // 1: pb_rpc_cache.ReqCacheLookup
	(*RepCacheLookup)(nil), // 2: pb_rpc_cache.RepCacheLookup
}
var file_pb_rpc_cache_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_rpc_cache_proto_init() }
func file_pb_rpc_cache_proto_init() {
	if File_pb_rpc_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_cache_proto_rawDesc), len(file_pb_rpc_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_cache_proto_goTypes,
		DependencyIndexes: file_pb_rpc_cache_proto_depIdxs,
		EnumInfos:         file_pb_rpc_cache_proto_enumTypes,
		MessageInfos:      file_pb_rpc_cache_proto_msgTypes,
	}.Build()
	File_pb_rpc_cache_proto = out.File
	file_pb_rpc_cache_proto_goTypes = nil
	file_pb_rpc_cache_proto_depIdxs = nil
}
