// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_cs_reward.proto

package pb_cs_reward

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 展示类型
type ShowType int32

const (
	ShowType_None   ShowType = 0 // 不展示
	ShowType_Common ShowType = 1 // 通用弹窗
)

// Enum value maps for ShowType.
var (
	ShowType_name = map[int32]string{
		0: "None",
		1: "Common",
	}
	ShowType_value = map[string]int32{
		"None":   0,
		"Common": 1,
	}
)

func (x ShowType) Enum() *ShowType {
	p := new(ShowType)
	*p = x
	return p
}

func (x ShowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShowType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_cs_reward_proto_enumTypes[0].Descriptor()
}

func (ShowType) Type() protoreflect.EnumType {
	return &file_pb_cs_reward_proto_enumTypes[0]
}

func (x ShowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShowType.Descriptor instead.
func (ShowType) EnumDescriptor() ([]byte, []int) {
	return file_pb_cs_reward_proto_rawDescGZIP(), []int{0}
}

// 道具奖励列表
type ItemReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         uint32                 `protobuf:"varint,1,opt,name=CfgId,proto3" json:"CfgId,omitempty"`       // 配置ID
	StackNum      uint64                 `protobuf:"varint,2,opt,name=StackNum,proto3" json:"StackNum,omitempty"` // 数量
	Grade         uint32                 `protobuf:"varint,3,opt,name=Grade,proto3" json:"Grade,omitempty"`       // 品质
	Level         uint32                 `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`       // 等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReward) Reset() {
	*x = ItemReward{}
	mi := &file_pb_cs_reward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReward) ProtoMessage() {}

func (x *ItemReward) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_reward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReward.ProtoReflect.Descriptor instead.
func (*ItemReward) Descriptor() ([]byte, []int) {
	return file_pb_cs_reward_proto_rawDescGZIP(), []int{0}
}

func (x *ItemReward) GetCfgId() uint32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *ItemReward) GetStackNum() uint64 {
	if x != nil {
		return x.StackNum
	}
	return 0
}

func (x *ItemReward) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ItemReward) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 奖励弹窗
type RepShowRewards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowType      ShowType               `protobuf:"varint,1,opt,name=ShowType,proto3,enum=pb_cs_reward.ShowType" json:"ShowType,omitempty"` // 展示类型
	Rewards       []*ItemReward          `protobuf:"bytes,2,rep,name=Rewards,proto3" json:"Rewards,omitempty"`                               // 奖励列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepShowRewards) Reset() {
	*x = RepShowRewards{}
	mi := &file_pb_cs_reward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepShowRewards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepShowRewards) ProtoMessage() {}

func (x *RepShowRewards) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cs_reward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepShowRewards.ProtoReflect.Descriptor instead.
func (*RepShowRewards) Descriptor() ([]byte, []int) {
	return file_pb_cs_reward_proto_rawDescGZIP(), []int{1}
}

func (x *RepShowRewards) GetShowType() ShowType {
	if x != nil {
		return x.ShowType
	}
	return ShowType_None
}

func (x *RepShowRewards) GetRewards() []*ItemReward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

var File_pb_cs_reward_proto protoreflect.FileDescriptor

const file_pb_cs_reward_proto_rawDesc = "" +
	"\n" +
	"\x12pb_cs_reward.proto\x12\fpb_cs_reward\"j\n" +
	"\n" +
	"ItemReward\x12\x14\n" +
	"\x05CfgId\x18\x01 \x01(\rR\x05CfgId\x12\x1a\n" +
	"\bStackNum\x18\x02 \x01(\x04R\bStackNum\x12\x14\n" +
	"\x05Grade\x18\x03 \x01(\rR\x05Grade\x12\x14\n" +
	"\x05Level\x18\x04 \x01(\rR\x05Level\"x\n" +
	"\x0eRepShowRewards\x122\n" +
	"\bShowType\x18\x01 \x01(\x0e2\x16.pb_cs_reward.ShowTypeR\bShowType\x122\n" +
	"\aRewards\x18\x02 \x03(\v2\x18.pb_cs_reward.ItemRewardR\aRewards* \n" +
	"\bShowType\x12\b\n" +
	"\x04None\x10\x00\x12\n" +
	"\n" +
	"\x06Common\x10\x01B\x19Z\x17game/pb/cs/pb_cs_rewardb\x06proto3"

var (
	file_pb_cs_reward_proto_rawDescOnce sync.Once
	file_pb_cs_reward_proto_rawDescData []byte
)

func file_pb_cs_reward_proto_rawDescGZIP() []byte {
	file_pb_cs_reward_proto_rawDescOnce.Do(func() {
		file_pb_cs_reward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cs_reward_proto_rawDesc), len(file_pb_cs_reward_proto_rawDesc)))
	})
	return file_pb_cs_reward_proto_rawDescData
}

var file_pb_cs_reward_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_cs_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_cs_reward_proto_goTypes = []any{
	(ShowType)(0),          // 0: pb_cs_reward.ShowType
	(*ItemReward)(nil),     // 1: pb_cs_reward.ItemReward
	(*RepShowRewards)(nil), // 2: pb_cs_reward.RepShowRewards
}
var file_pb_cs_reward_proto_depIdxs = []int32{
	0, // 0: pb_cs_reward.RepShowRewards.ShowType:type_name -> pb_cs_reward.ShowType
	1, // 1: pb_cs_reward.RepShowRewards.Rewards:type_name -> pb_cs_reward.ItemReward
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_cs_reward_proto_init() }
func file_pb_cs_reward_proto_init() {
	if File_pb_cs_reward_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cs_reward_proto_rawDesc), len(file_pb_cs_reward_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_cs_reward_proto_goTypes,
		DependencyIndexes: file_pb_cs_reward_proto_depIdxs,
		EnumInfos:         file_pb_cs_reward_proto_enumTypes,
		MessageInfos:      file_pb_cs_reward_proto_msgTypes,
	}.Build()
	File_pb_cs_reward_proto = out.File
	file_pb_cs_reward_proto_goTypes = nil
	file_pb_cs_reward_proto_depIdxs = nil
}
