// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: pb_rpc_pay.proto

package pb_rpc_pay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发货请求
type ReqPayBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerId         uint32                 `protobuf:"varint,1,opt,name=SerId,proto3" json:"SerId,omitempty"`               // 服务器ID
	Sid           uint32                 `protobuf:"varint,2,opt,name=Sid,proto3" json:"Sid,omitempty"`                   // 玩家ID
	Sdk           uint32                 `protobuf:"varint,3,opt,name=Sdk,proto3" json:"Sdk,omitempty"`                   // sdk
	GameOrder     uint64                 `protobuf:"varint,4,opt,name=GameOrder,proto3" json:"GameOrder,omitempty"`       // 游戏订单
	ActType       uint32                 `protobuf:"varint,5,opt,name=ActType,proto3" json:"ActType,omitempty"`           // 活动类型
	ActId         uint32                 `protobuf:"varint,6,opt,name=ActId,proto3" json:"ActId,omitempty"`               // 活动ID
	ActProductId  uint32                 `protobuf:"varint,7,opt,name=ActProductId,proto3" json:"ActProductId,omitempty"` // 活动商品ID
	SdkProductId  string                 `protobuf:"bytes,8,opt,name=SdkProductId,proto3" json:"SdkProductId,omitempty"`  // sdk商品ID(后台商品ID)
	SdkOrder      string                 `protobuf:"bytes,9,opt,name=SdkOrder,proto3" json:"SdkOrder,omitempty"`          // sdk订单号
	Currency      string                 `protobuf:"bytes,10,opt,name=Currency,proto3" json:"Currency,omitempty"`         // 货币类型
	Money         uint32                 `protobuf:"varint,11,opt,name=Money,proto3" json:"Money,omitempty"`              // 价格(分)
	PayChannel    string                 `protobuf:"bytes,12,opt,name=PayChannel,proto3" json:"PayChannel,omitempty"`     // 支付渠道
	PayUser       string                 `protobuf:"bytes,13,opt,name=PayUser,proto3" json:"PayUser,omitempty"`           // 支付的sdk账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPayBack) Reset() {
	*x = ReqPayBack{}
	mi := &file_pb_rpc_pay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPayBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPayBack) ProtoMessage() {}

func (x *ReqPayBack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_pay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPayBack.ProtoReflect.Descriptor instead.
func (*ReqPayBack) Descriptor() ([]byte, []int) {
	return file_pb_rpc_pay_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPayBack) GetSerId() uint32 {
	if x != nil {
		return x.SerId
	}
	return 0
}

func (x *ReqPayBack) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ReqPayBack) GetSdk() uint32 {
	if x != nil {
		return x.Sdk
	}
	return 0
}

func (x *ReqPayBack) GetGameOrder() uint64 {
	if x != nil {
		return x.GameOrder
	}
	return 0
}

func (x *ReqPayBack) GetActType() uint32 {
	if x != nil {
		return x.ActType
	}
	return 0
}

func (x *ReqPayBack) GetActId() uint32 {
	if x != nil {
		return x.ActId
	}
	return 0
}

func (x *ReqPayBack) GetActProductId() uint32 {
	if x != nil {
		return x.ActProductId
	}
	return 0
}

func (x *ReqPayBack) GetSdkProductId() string {
	if x != nil {
		return x.SdkProductId
	}
	return ""
}

func (x *ReqPayBack) GetSdkOrder() string {
	if x != nil {
		return x.SdkOrder
	}
	return ""
}

func (x *ReqPayBack) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ReqPayBack) GetMoney() uint32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *ReqPayBack) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *ReqPayBack) GetPayUser() string {
	if x != nil {
		return x.PayUser
	}
	return ""
}

// 发货成功返回
type RepPayBack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameOrder     uint64                 `protobuf:"varint,1,opt,name=GameOrder,proto3" json:"GameOrder,omitempty"` // 游戏订单
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepPayBack) Reset() {
	*x = RepPayBack{}
	mi := &file_pb_rpc_pay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepPayBack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepPayBack) ProtoMessage() {}

func (x *RepPayBack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rpc_pay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepPayBack.ProtoReflect.Descriptor instead.
func (*RepPayBack) Descriptor() ([]byte, []int) {
	return file_pb_rpc_pay_proto_rawDescGZIP(), []int{1}
}

func (x *RepPayBack) GetGameOrder() uint64 {
	if x != nil {
		return x.GameOrder
	}
	return 0
}

var File_pb_rpc_pay_proto protoreflect.FileDescriptor

const file_pb_rpc_pay_proto_rawDesc = "" +
	"\n" +
	"\x10pb_rpc_pay.proto\x12\n" +
	"pb_rpc_pay\"\xe4\x02\n" +
	"\n" +
	"ReqPayBack\x12\x14\n" +
	"\x05SerId\x18\x01 \x01(\rR\x05SerId\x12\x10\n" +
	"\x03Sid\x18\x02 \x01(\rR\x03Sid\x12\x10\n" +
	"\x03Sdk\x18\x03 \x01(\rR\x03Sdk\x12\x1c\n" +
	"\tGameOrder\x18\x04 \x01(\x04R\tGameOrder\x12\x18\n" +
	"\aActType\x18\x05 \x01(\rR\aActType\x12\x14\n" +
	"\x05ActId\x18\x06 \x01(\rR\x05ActId\x12\"\n" +
	"\fActProductId\x18\a \x01(\rR\fActProductId\x12\"\n" +
	"\fSdkProductId\x18\b \x01(\tR\fSdkProductId\x12\x1a\n" +
	"\bSdkOrder\x18\t \x01(\tR\bSdkOrder\x12\x1a\n" +
	"\bCurrency\x18\n" +
	" \x01(\tR\bCurrency\x12\x14\n" +
	"\x05Money\x18\v \x01(\rR\x05Money\x12\x1e\n" +
	"\n" +
	"PayChannel\x18\f \x01(\tR\n" +
	"PayChannel\x12\x18\n" +
	"\aPayUser\x18\r \x01(\tR\aPayUser\"*\n" +
	"\n" +
	"RepPayBack\x12\x1c\n" +
	"\tGameOrder\x18\x01 \x01(\x04R\tGameOrderB\x18Z\x16game/pb/rpc/pb_rpc_payb\x06proto3"

var (
	file_pb_rpc_pay_proto_rawDescOnce sync.Once
	file_pb_rpc_pay_proto_rawDescData []byte
)

func file_pb_rpc_pay_proto_rawDescGZIP() []byte {
	file_pb_rpc_pay_proto_rawDescOnce.Do(func() {
		file_pb_rpc_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rpc_pay_proto_rawDesc), len(file_pb_rpc_pay_proto_rawDesc)))
	})
	return file_pb_rpc_pay_proto_rawDescData
}

var file_pb_rpc_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_rpc_pay_proto_goTypes = []any{
	(*ReqPayBack)(nil), // 0: pb_rpc_pay.ReqPayBack
	(*RepPayBack)(nil), // 1: pb_rpc_pay.RepPayBack
}
var file_pb_rpc_pay_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_rpc_pay_proto_init() }
func file_pb_rpc_pay_proto_init() {
	if File_pb_rpc_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rpc_pay_proto_rawDesc), len(file_pb_rpc_pay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_rpc_pay_proto_goTypes,
		DependencyIndexes: file_pb_rpc_pay_proto_depIdxs,
		MessageInfos:      file_pb_rpc_pay_proto_msgTypes,
	}.Build()
	File_pb_rpc_pay_proto = out.File
	file_pb_rpc_pay_proto_goTypes = nil
	file_pb_rpc_pay_proto_depIdxs = nil
}
